<?php

use Illuminate\Database\Seeder;

class LocalidadesTlaxcalaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

         DB::table('cat_localidad')->insert([
            ['idMunicipio'=>2028,'nombre' =>'AMAXAC DE GUERRERO'],
            ['idMunicipio'=>2028,'nombre' =>'SAN DAMIAN TLACOCALPAN'],
            ['idMunicipio'=>2028,'nombre' =>'LA PRECIOSA [RANCHO]'],
            ['idMunicipio'=>2029,'nombre' =>'APETATITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'BELEN ATZITZIMITITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'SAN MATIAS TEPETOMATITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'TECOLOTLA'],
            ['idMunicipio'=>2029,'nombre' =>'TLATEMPAN'],
            ['idMunicipio'=>2029,'nombre' =>'LA LOMA [COLONIA]'],
            ['idMunicipio'=>2030,'nombre' =>'ATLANGATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA SAN JOSE ATLANGA'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA AGRICOLA SAN LUIS'],
            ['idMunicipio'=>2030,'nombre' =>'SAN PEDRO ECATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA AGRICOLA SANTA CLARA OZUMBA'],
            ['idMunicipio'=>2030,'nombre' =>'SANTA MARIA TEPETZALA'],
            ['idMunicipio'=>2030,'nombre' =>'SAN JOSE DE SANTA ROSA ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA SAN ANTONIO TEPETZALA'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA BENITO JUAREZ (TEZOYO)'],
            ['idMunicipio'=>2030,'nombre' =>'LA TRASQUILA'],
            ['idMunicipio'=>2030,'nombre' =>'SANTIAGO VILLALTA'],
            ['idMunicipio'=>2030,'nombre' =>'VISTA HERMOSA'],
            ['idMunicipio'=>2030,'nombre' =>'ZUMPANGO'],
            ['idMunicipio'=>2030,'nombre' =>'EL PARAISO'],
            ['idMunicipio'=>2030,'nombre' =>'LA CAÑADA'],
            ['idMunicipio'=>2030,'nombre' =>'CERRO DE LAS FLORES'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA LA TRASQUILA'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTAL'],
            ['idMunicipio'=>2030,'nombre' =>'SANTA ELENA'],
            ['idMunicipio'=>2030,'nombre' =>'VILLA DE LAS FLORES'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA LOMA BONITA'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO JERICO'],
            ['idMunicipio'=>2030,'nombre' =>'SAN ANTONIO ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'XUXTEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'LA FLOR [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'CUARTA FRACCION DE OLIVARES'],
            ['idMunicipio'=>2030,'nombre' =>'LA CUCHILLA (EL ALCANFOR)'],
            ['idMunicipio'=>2030,'nombre' =>'FRACCION SAN PEDRO ECATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'VILLA QUINTA OLIVARES [CENTRO VACACIONAL]'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO XALNENE'],
            ['idMunicipio'=>2030,'nombre' =>'LA HERRADURA [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN ANTONIO (LA ESPERANZA)'],
            ['idMunicipio'=>2030,'nombre' =>'SAN JOSE ATLANGA'],
            ['idMunicipio'=>2030,'nombre' =>'TEPEZILAPAN'],
            ['idMunicipio'=>2030,'nombre' =>'TERCERA FRACCION DE OLIVARES'],
            ['idMunicipio'=>2030,'nombre' =>'LA TROJE'],
            ['idMunicipio'=>2030,'nombre' =>'EL CATORCE'],
            ['idMunicipio'=>2030,'nombre' =>'EL HUERFANO'],
            ['idMunicipio'=>2030,'nombre' =>'EL LLANO DE XUXTEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE (EL JAGÜEY)'],
            ['idMunicipio'=>2030,'nombre' =>'EL ENCINO [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL POTRERO [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LAS BARRANCAS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LAS TINAJAS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS CAPULINES [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS ENCINOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS NOPALITOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN SIMON'],
            ['idMunicipio'=>2030,'nombre' =>'LAS TINAJAS (LA TEPOZANERA)'],
            ['idMunicipio'=>2030,'nombre' =>'LUIS ECHEVERRIA [ESTABLO BOVINO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2030,'nombre' =>'LA PROVIDENCIA'],
            ['idMunicipio'=>2030,'nombre' =>'SAMUEL OREA (RANCHO EL PATO)'],
            ['idMunicipio'=>2030,'nombre' =>'LA JOYA'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO GUADALUPE'],
            ['idMunicipio'=>2030,'nombre' =>'UNIDAD HABITACIONAL I'],
            ['idMunicipio'=>2030,'nombre' =>'ALMEYA'],
            ['idMunicipio'=>2030,'nombre' =>'EL CAPRICHO'],
            ['idMunicipio'=>2030,'nombre' =>'EL COLIBRI'],
            ['idMunicipio'=>2030,'nombre' =>'EL HERRADERO'],
            ['idMunicipio'=>2030,'nombre' =>'LA VACA PRIETA'],
            ['idMunicipio'=>2030,'nombre' =>'LOS CUATRO HERMANOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN PEDRO ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'LOS TRES POCILLOS'],
            ['idMunicipio'=>2030,'nombre' =>'CAMINO REAL'],
            ['idMunicipio'=>2030,'nombre' =>'JESUS GARCIA'],
            ['idMunicipio'=>2030,'nombre' =>'TERCERA SECCION DE BAIVER'],
            ['idMunicipio'=>2031,'nombre' =>'ATLZAYANCA'],
            ['idMunicipio'=>2031,'nombre' =>'SAN FRANCISCO AXOPILCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE BUENAVISTA'],
            ['idMunicipio'=>2031,'nombre' =>'CONCEPCION HIDALGO'],
            ['idMunicipio'=>2031,'nombre' =>'FELIPE CARRILLO PUERTO'],
            ['idMunicipio'=>2031,'nombre' =>'LA GARITA'],
            ['idMunicipio'=>2031,'nombre' =>'LAZARO CARDENAS'],
            ['idMunicipio'=>2031,'nombre' =>'MESA REDONDA'],
            ['idMunicipio'=>2031,'nombre' =>'MIAHUAPAN EL BAJO'],
            ['idMunicipio'=>2031,'nombre' =>'NEXNOPALA'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHO OCOTLA'],
            ['idMunicipio'=>2031,'nombre' =>'LA RINCONA'],
            ['idMunicipio'=>2031,'nombre' =>'SAN ANTONIO TECOPILCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE XALASCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JUAN OCOTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA CRUZ POCITOS'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA MARIA LAS CUEVAS'],
            ['idMunicipio'=>2031,'nombre' =>'XALTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'COLONIA DELICIAS'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE PILANCON'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHO BLANCO'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHERIA DE POCITOS'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA MARTHA [RANCHO]'],
            ['idMunicipio'=>2031,'nombre' =>'CARRETA'],
            ['idMunicipio'=>2031,'nombre' =>'XARERO XALTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'MAZEHUALPA'],
            ['idMunicipio'=>2031,'nombre' =>'LOMA DE JUNGUITO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN MIGUEL FRANCO [RANCHERIA]'],
            ['idMunicipio'=>2031,'nombre' =>'MIAHUAPAN EL ALTO'],
            ['idMunicipio'=>2031,'nombre' =>'COLONIA NAZARETH'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE MIRAVALLE'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA CRUZ [RANCHO]'],
            ['idMunicipio'=>2031,'nombre' =>'FRACCION CERON (TONALACO)'],
            ['idMunicipio'=>2031,'nombre' =>'LA SOLEDAD LOMA DE OCOTLA [RANCHERIA]'],
            ['idMunicipio'=>2031,'nombre' =>'AMPARITO'],
            ['idMunicipio'=>2031,'nombre' =>'LOS OCALITOS'],
            ['idMunicipio'=>2031,'nombre' =>'MARIANO GUARNEROS ARROYO'],
            ['idMunicipio'=>2031,'nombre' =>'AURELIO AGUILAR'],
            ['idMunicipio'=>2031,'nombre' =>'FRACCION CERON'],
            ['idMunicipio'=>2031,'nombre' =>'JOSE FERNANDEZ'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JERONIMO ZACUALPAN'],
            ['idMunicipio'=>2031,'nombre' =>'TECHACHALCO'],
            ['idMunicipio'=>2031,'nombre' =>'HUERTA LIZET'],
            ['idMunicipio'=>2031,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2031,'nombre' =>'SANTO DOMINGO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN ANTONIO [BARRIO]'],
            ['idMunicipio'=>2032,'nombre' =>'CIUDAD DE APIZACO'],
            ['idMunicipio'=>2032,'nombre' =>'CERRITO DE GUADALUPE'],
            ['idMunicipio'=>2032,'nombre' =>'GUADALUPE TEXCALAC'],
            ['idMunicipio'=>2032,'nombre' =>'JAGÜEY PRIETO'],
            ['idMunicipio'=>2032,'nombre' =>'JOSE MARIA MORELOS'],
            ['idMunicipio'=>2032,'nombre' =>'COLONIA SAN ISIDRO'],
            ['idMunicipio'=>2032,'nombre' =>'SAN LUIS APIZAQUITO'],
            ['idMunicipio'=>2032,'nombre' =>'SANTA ANITA HUILOAC'],
            ['idMunicipio'=>2032,'nombre' =>'SANTA MARIA TEXCALAC'],
            ['idMunicipio'=>2032,'nombre' =>'ACTIPAN'],
            ['idMunicipio'=>2032,'nombre' =>'ATENCO'],
            ['idMunicipio'=>2032,'nombre' =>'EJIDO DE SAN DIONISIO'],
            ['idMunicipio'=>2032,'nombre' =>'LOS GEMELOS [RANCHO]'],
            ['idMunicipio'=>2032,'nombre' =>'PARADA DE LA VIRGEN'],
            ['idMunicipio'=>2032,'nombre' =>'SAN JOSE TETEL (LA QUEBRADORA)'],
            ['idMunicipio'=>2032,'nombre' =>'FRANCISCO MORENO MORALES'],
            ['idMunicipio'=>2032,'nombre' =>'CUARTA MANZANA'],
            ['idMunicipio'=>2032,'nombre' =>'TOCHAC'],
            ['idMunicipio'=>2032,'nombre' =>'LA VIA (COLONIA EL SILBATO)'],
            ['idMunicipio'=>2032,'nombre' =>'UNIDAD DEPORTIVA'],
            ['idMunicipio'=>2032,'nombre' =>'FRACCIONAMIENTO JARDINES DE SAN FRANCISCO'],
            ['idMunicipio'=>2032,'nombre' =>'CUARTA SECCION'],
            ['idMunicipio'=>2032,'nombre' =>'EJIDO DE SANTA ÚRSULA'],
            ['idMunicipio'=>2032,'nombre' =>'PRIMERA SECCION'],
            ['idMunicipio'=>2033,'nombre' =>'CALPULALPAN'],
            ['idMunicipio'=>2033,'nombre' =>'AMANTLA'],
            ['idMunicipio'=>2033,'nombre' =>'COECILLOS'],
            ['idMunicipio'=>2033,'nombre' =>'EL CARMEN'],
            ['idMunicipio'=>2033,'nombre' =>'MAZAPA'],
            ['idMunicipio'=>2033,'nombre' =>'SAN BARTOLOME DEL MONTE'],
            ['idMunicipio'=>2033,'nombre' =>'SAN CRISTOBAL ZACACALCO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN FELIPE SULTEPEC'],
            ['idMunicipio'=>2033,'nombre' =>'LOS TRES HERMANOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MARCOS GUAQUILPAN'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MATEO ATICPAC'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA CATALINA'],
            ['idMunicipio'=>2033,'nombre' =>'SANTIAGO CUAULA'],
            ['idMunicipio'=>2033,'nombre' =>'LA SOLEDAD'],
            ['idMunicipio'=>2033,'nombre' =>'NCPE GUSTAVO DIAZ ORDAZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOS PALACIOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN TEMAZCALES'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA CRUZ'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA TERESA'],
            ['idMunicipio'=>2033,'nombre' =>'LA VENTA'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JOSE'],
            ['idMunicipio'=>2033,'nombre' =>'LOS PINOS'],
            ['idMunicipio'=>2033,'nombre' =>'HERMANOS GARCIA'],
            ['idMunicipio'=>2033,'nombre' =>'MONTE DE SAN AGUSTIN'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO HERMENEGILDO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS DALIAS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA FELIX'],
            ['idMunicipio'=>2033,'nombre' =>'LOS DIAZ'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN MORALES (LA VENTILLA)'],
            ['idMunicipio'=>2033,'nombre' =>'LA VENTILLA'],
            ['idMunicipio'=>2033,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2033,'nombre' =>'LOS MOGOTES'],
            ['idMunicipio'=>2033,'nombre' =>'LA QUEBRADORA'],
            ['idMunicipio'=>2033,'nombre' =>'POZO SAN VICENTE [RESTAURANTE]'],
            ['idMunicipio'=>2033,'nombre' =>'DAVID SANCHEZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOS MEJIA'],
            ['idMunicipio'=>2033,'nombre' =>'EL CACALOTE'],
            ['idMunicipio'=>2033,'nombre' =>'LA PALMA'],
            ['idMunicipio'=>2033,'nombre' =>'LA HONDONADA'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO CACHO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS AURAS'],
            ['idMunicipio'=>2033,'nombre' =>'LA FLOR'],
            ['idMunicipio'=>2033,'nombre' =>'EL ROSARIO (PARADA LA CAPILLA)'],
            ['idMunicipio'=>2033,'nombre' =>'LA BLANCA'],
            ['idMunicipio'=>2033,'nombre' =>'PUENTE DEL OCOMIQUE'],
            ['idMunicipio'=>2033,'nombre' =>'DON RAMON'],
            ['idMunicipio'=>2033,'nombre' =>'EL CARMEN [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'MARCELINO CRUZ'],
            ['idMunicipio'=>2033,'nombre' =>'LA MORENA'],
            ['idMunicipio'=>2033,'nombre' =>'LOMA BONITA'],
            ['idMunicipio'=>2033,'nombre' =>'RAYMUNDO ÁLVAREZ GUERRERO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO BONITO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO DEL VENADO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2033,'nombre' =>'SAN VICENTE'],
            ['idMunicipio'=>2033,'nombre' =>'SAN ANTONIO (SAN PEDRO)'],
            ['idMunicipio'=>2033,'nombre' =>'CAMINO A SAN VICENTE'],
            ['idMunicipio'=>2033,'nombre' =>'JOSE DIAZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOMA DE SAN AGUSTIN'],
            ['idMunicipio'=>2033,'nombre' =>'ALEJANDRO HERNANDEZ'],
            ['idMunicipio'=>2033,'nombre' =>'LA OCOTERA [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'DOLORES'],
            ['idMunicipio'=>2033,'nombre' =>'EL CONVENTO DE LA SOLEDAD'],
            ['idMunicipio'=>2033,'nombre' =>'EL DURAZNO'],
            ['idMunicipio'=>2033,'nombre' =>'ERNESTO ALONSO'],
            ['idMunicipio'=>2033,'nombre' =>'ESPERANZA ORTIZ'],
            ['idMunicipio'=>2033,'nombre' =>'GABRIEL ROLDAN'],
            ['idMunicipio'=>2033,'nombre' =>'GRANJA DEL POZO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN RODRIGO'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN HERNANDEZ (RANCHO EL SOLITARIO)'],
            ['idMunicipio'=>2033,'nombre' =>'LAS PALOMAS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN PEDRO'],
            ['idMunicipio'=>2033,'nombre' =>'RODOLFO ÁVILA'],
            ['idMunicipio'=>2033,'nombre' =>'SAMUEL LABASTIDA'],
            ['idMunicipio'=>2033,'nombre' =>'EL TRIANGULO'],
            ['idMunicipio'=>2033,'nombre' =>'ÁNGEL PELCASTRE'],
            ['idMunicipio'=>2033,'nombre' =>'HERMANOS ÁVILA'],
            ['idMunicipio'=>2033,'nombre' =>'JACARANDAS'],
            ['idMunicipio'=>2033,'nombre' =>'EL MIRADOR DOS'],
            ['idMunicipio'=>2033,'nombre' =>'ANALCO DOS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA ROSA'],
            ['idMunicipio'=>2033,'nombre' =>'COLA DEL POTRERO'],
            ['idMunicipio'=>2033,'nombre' =>'PACHECO (DE LA ROSA)'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN DE LOS LAGOS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA ISABEL MIXTITLAN'],
            ['idMunicipio'=>2033,'nombre' =>'EMILIO LOPEZ'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN ZAVALA'],
            ['idMunicipio'=>2033,'nombre' =>'PARADOR KILOMETRO 57'],
            ['idMunicipio'=>2033,'nombre' =>'SAN FRANCISCO'],
            ['idMunicipio'=>2033,'nombre' =>'EL PIÑON'],
            ['idMunicipio'=>2033,'nombre' =>'ALBINO ALONSO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS TRES V'],
            ['idMunicipio'=>2033,'nombre' =>'LOS POTRILLOS [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'LA ESPERANZA'],
            ['idMunicipio'=>2033,'nombre' =>'EL ÁLAMO'],
            ['idMunicipio'=>2033,'nombre' =>'ARTURO OLMEDO'],
            ['idMunicipio'=>2033,'nombre' =>'HOSPITAL GENERAL DE CALPULALPAN'],
            ['idMunicipio'=>2033,'nombre' =>'PARADA COECILLOS'],
            ['idMunicipio'=>2033,'nombre' =>'EL REGALO [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO ESCONDIDO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO PAJARITOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN ALEJANDRO [RANCHO]'],
            ['idMunicipio'=>2034,'nombre' =>'VILLA DE EL CARMEN TEQUEXQUITLA'],
            ['idMunicipio'=>2034,'nombre' =>'LA SOLEDAD'],
            ['idMunicipio'=>2034,'nombre' =>'OCOTLAN TEMALACAYUCAN'],
            ['idMunicipio'=>2034,'nombre' =>'COLONIA VICENTE GUERRERO'],
            ['idMunicipio'=>2034,'nombre' =>'BARRIO DE GUADALUPE'],
            ['idMunicipio'=>2035,'nombre' =>'CUAPIAXTLA'],
            ['idMunicipio'=>2035,'nombre' =>'LA ASUNCION RASCONA'],
            ['idMunicipio'=>2035,'nombre' =>'EGIPTO'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA IGNACIO ALLENDE'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA JOSE MARIA MORELOS'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA MANUEL ÁVILA CAMACHO'],
            ['idMunicipio'=>2035,'nombre' =>'PLAN DE AYALA'],
            ['idMunicipio'=>2035,'nombre' =>'EX-HACIENDA SAN FRANCISCO CUEXCOMATEPEC'],
            ['idMunicipio'=>2035,'nombre' =>'SAN FRANCISCO CUEXCONTZI'],
            ['idMunicipio'=>2035,'nombre' =>'SAN FELIPE TEOMETITLA'],
            ['idMunicipio'=>2035,'nombre' =>'RANCHO MAZARRAZA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN MIGUEL TEOMETITLA'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA FE UNO'],
            ['idMunicipio'=>2035,'nombre' =>'EL TEJOCOTE'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA LOMA BONITA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN RAFAEL TEPATLAXCO (UNION Y PROGRESO)'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA BEATRIZ LA NUEVA'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA REBECA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN DIEGO COYOTEPEC'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA DEL VALLE'],
            ['idMunicipio'=>2035,'nombre' =>'GRANJA DE GUADALUPE'],
            ['idMunicipio'=>2035,'nombre' =>'FRACCION CERON'],
            ['idMunicipio'=>2035,'nombre' =>'TECOAC [GRANJA PORCINA]'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA NAZARETH'],
            ['idMunicipio'=>2035,'nombre' =>'EJIDO DE ALLENDE'],
            ['idMunicipio'=>2035,'nombre' =>'LA GRANJA (CAMINO A FRANCO)'],
            ['idMunicipio'=>2035,'nombre' =>'PALMA DE TRES BRAZOS (FRACCION SANTO DOMINGO)'],
            ['idMunicipio'=>2035,'nombre' =>'RANCHO CERON'],
            ['idMunicipio'=>2035,'nombre' =>'FACTOR FELIX LOPEZ'],
            ['idMunicipio'=>2036,'nombre' =>'CUAXOMULCO'],
            ['idMunicipio'=>2036,'nombre' =>'SAN MIGUEL BUENAVISTA'],
            ['idMunicipio'=>2036,'nombre' =>'SAN LORENZO XALTELULCO'],
            ['idMunicipio'=>2036,'nombre' =>'ZACAMOLPA'],
            ['idMunicipio'=>2036,'nombre' =>'COXTLA'],
            ['idMunicipio'=>2036,'nombre' =>'TECOLA'],
            ['idMunicipio'=>2037,'nombre' =>'SANTA ANA CHIAUTEMPAN'],
            ['idMunicipio'=>2037,'nombre' =>'SAN PEDRO MUÑOZTLA'],
            ['idMunicipio'=>2037,'nombre' =>'SAN BARTOLOME CUAHUIXMATLAC'],
            ['idMunicipio'=>2037,'nombre' =>'SAN RAFAEL TEPATLAXCO'],
            ['idMunicipio'=>2037,'nombre' =>'SANTA CRUZ TETELA'],
            ['idMunicipio'=>2037,'nombre' =>'SAN PEDRO TLALCUAPAN DE NICOLAS BRAVO'],
            ['idMunicipio'=>2037,'nombre' =>'SAN PEDRO XOCHITEOTLA'],
            ['idMunicipio'=>2037,'nombre' =>'SAN ANTOÑOTLA'],
            ['idMunicipio'=>2037,'nombre' =>'SANTA FE ESPERANZA'],
            ['idMunicipio'=>2037,'nombre' =>'TECTEYOC'],
            ['idMunicipio'=>2037,'nombre' =>'LA PRESA IXCOTLA'],
            ['idMunicipio'=>2037,'nombre' =>'LA PRESA DE SAN BARTOLO (EL VADO)'],
            ['idMunicipio'=>2037,'nombre' =>'ALCOTITLA (XALTIPAN)'],
            ['idMunicipio'=>2037,'nombre' =>'COLONIA LIBERTAD'],
            ['idMunicipio'=>2037,'nombre' =>'AHUEHUEHIAC'],
            ['idMunicipio'=>2037,'nombre' =>'POTRERO CALZOLC'],
            ['idMunicipio'=>2037,'nombre' =>'MEMETLA'],
            ['idMunicipio'=>2037,'nombre' =>'TONANTZINCO'],
            ['idMunicipio'=>2038,'nombre' =>'MUÑOZ'],
            ['idMunicipio'=>2038,'nombre' =>'LOS ÁLAMOS'],
            ['idMunicipio'=>2038,'nombre' =>'SAN BARTOLO CUAMANTZINGO'],
            ['idMunicipio'=>2038,'nombre' =>'SAN ISIDRO CHIPILA'],
            ['idMunicipio'=>2038,'nombre' =>'ESTACION GUADALUPE'],
            ['idMunicipio'=>2038,'nombre' =>'GUADALUPE CUAUHTEMOC'],
            ['idMunicipio'=>2038,'nombre' =>'SAN JOSE CUAMANTZINGO'],
            ['idMunicipio'=>2038,'nombre' =>'EX-HACIENDA DE GUADALUPE'],
            ['idMunicipio'=>2038,'nombre' =>'EJIDO MUÑOZ'],
            ['idMunicipio'=>2038,'nombre' =>'EJIDO SAN MARTIN XALTOCAN'],
            ['idMunicipio'=>2038,'nombre' =>'LOS MAIZALES [RANCHO]'],
            ['idMunicipio'=>2038,'nombre' =>'EJIDO DE ZACATEPEC'],
            ['idMunicipio'=>2038,'nombre' =>'LA LOMA DE ZACATEPEC'],
            ['idMunicipio'=>2038,'nombre' =>'RANCHO LA BODEGA'],
            ['idMunicipio'=>2038,'nombre' =>'SAN JUAN DEL RIO [RANCHO]'],
            ['idMunicipio'=>2038,'nombre' =>'JAVIER ZAPATA'],
            ['idMunicipio'=>2039,'nombre' =>'ESPAÑITA'],
            ['idMunicipio'=>2039,'nombre' =>'ÁLVARO OBREGON'],
            ['idMunicipio'=>2039,'nombre' =>'LA CONCEPCION'],
            ['idMunicipio'=>2039,'nombre' =>'LA CONSTANCIA'],
            ['idMunicipio'=>2039,'nombre' =>'FRANCISCO I. MADERO EL VIEJO'],
            ['idMunicipio'=>2039,'nombre' =>'LA JOYA'],
            ['idMunicipio'=>2039,'nombre' =>'LA MAGDALENA CUEXTOTITLA'],
            ['idMunicipio'=>2039,'nombre' =>'MIGUEL ALDAMA'],
            ['idMunicipio'=>2039,'nombre' =>'LAS PILAS'],
            ['idMunicipio'=>2039,'nombre' =>'LA REFORMA'],
            ['idMunicipio'=>2039,'nombre' =>'SAN AGUSTIN'],
            ['idMunicipio'=>2039,'nombre' =>'SAN FRANCISCO MITEPEC'],
            ['idMunicipio'=>2039,'nombre' =>'SAN JUAN MITEPEC'],
            ['idMunicipio'=>2039,'nombre' =>'SAN MIGUEL EL PIÑON'],
            ['idMunicipio'=>2039,'nombre' =>'SAN MIGUEL PIPIYOLA'],
            ['idMunicipio'=>2039,'nombre' =>'SAN MIGUEL TEPALCA'],
            ['idMunicipio'=>2039,'nombre' =>'VICENTE GUERRERO'],
            ['idMunicipio'=>2039,'nombre' =>'RANCHO LAGUNITAS'],
            ['idMunicipio'=>2039,'nombre' =>'BARRIO DE TORRES'],
            ['idMunicipio'=>2039,'nombre' =>'SAN ANTONIO'],
            ['idMunicipio'=>2039,'nombre' =>'SAN PABLO'],
            ['idMunicipio'=>2039,'nombre' =>'LA SOLEDAD [RANCHO]'],
            ['idMunicipio'=>2039,'nombre' =>'LOS CAPULINES'],
            ['idMunicipio'=>2039,'nombre' =>'POTRERO EL PIÑON'],
            ['idMunicipio'=>2039,'nombre' =>'LA VALENTINA'],
            ['idMunicipio'=>2039,'nombre' =>'RANCHO GUILLEN'],
            ['idMunicipio'=>2039,'nombre' =>'ASILO DE ANCIANOS SAN JUDAS TADEO'],
            ['idMunicipio'=>2039,'nombre' =>'EL AGUA SANTA (LAS TINAS)'],
            ['idMunicipio'=>2039,'nombre' =>'EL SABINAL'],
            ['idMunicipio'=>2039,'nombre' =>'LINDAVISTA'],
            ['idMunicipio'=>2039,'nombre' =>'JOSE LUIS TOVAR OLVERA'],
            ['idMunicipio'=>2039,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2039,'nombre' =>'PABLO GARCIA SANCHEZ (RANCHO TECUICUILCO)'],
            ['idMunicipio'=>2040,'nombre' =>'HUAMANTLA'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA ALTAMIRA GUADALUPE'],
            ['idMunicipio'=>2040,'nombre' =>'SAN PEDRO EL BATAN'],
            ['idMunicipio'=>2040,'nombre' =>'BENITO JUAREZ'],
            ['idMunicipio'=>2040,'nombre' =>'HUERTA DE LA TRINIDAD'],
            ['idMunicipio'=>2040,'nombre' =>'EL CARMEN XALPATLAHUAYA'],
            ['idMunicipio'=>2040,'nombre' =>'EX-HACIENDA LA COMPAÑIA'],
            ['idMunicipio'=>2040,'nombre' =>'LA PROVIDENCIA (EL CONQUIAN)'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA CUAUHTEMOC'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA CHAPULTEPEC'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA HERMENEGILDO GALEANA'],
            ['idMunicipio'=>2040,'nombre' =>'IGNACIO ZARAGOZA'],
            ['idMunicipio'=>2040,'nombre' =>'JOSE MARIA MORELOS'],
            ['idMunicipio'=>2040,'nombre' =>'LAZARO CARDENAS'],
            ['idMunicipio'=>2040,'nombre' =>'SAN MARTIN NOTARIO'],
            ['idMunicipio'=>2040,'nombre' =>'LOS PILARES'],
            ['idMunicipio'=>2040,'nombre' =>'SAN DIEGO MECA'],
            ['idMunicipio'=>2040,'nombre' =>'SAN FRANCISCO TECOAC [COLONIA]'],
            ['idMunicipio'=>2040,'nombre' =>'SAN MIGUEL VISTA HERMOSA [RANCHO]'],
            ['idMunicipio'=>2040,'nombre' =>'SAN MIGUEL BAEZ'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA ANA RIOS'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA CLARA SOTOLTEPEC'],
            ['idMunicipio'=>2040,'nombre' =>'NCP SAN JOSE TEACALCO'],
            ['idMunicipio'=>2040,'nombre' =>'RANCHERIA DE TORRES'],
            ['idMunicipio'=>2040,'nombre' =>'EX-HACIENDA SAN DIEGO XALPATLAHUAYA'],
            ['idMunicipio'=>2040,'nombre' =>'SAN JOSE XICOHTENCATL'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA MARIA MAGDALENA XONECUILA'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA EL VALLE'],
            ['idMunicipio'=>2040,'nombre' =>'NCP JOSE MARIA MORELOS'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA LICENCIADO MAURO ANGULO'],
            ['idMunicipio'=>2040,'nombre' =>'GENERAL FRANCISCO VILLA'],
            ['idMunicipio'=>2040,'nombre' =>'SAN CRISTOBAL DE LA LAGUNA'],
            ['idMunicipio'=>2040,'nombre' =>'LOS ÁLAMOS [RANCHO]'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA AGRICOLA SAN MARTIN NOTARIO'],
            ['idMunicipio'=>2040,'nombre' =>'LA LIMA [RANCHERIA]'],
            ['idMunicipio'=>2040,'nombre' =>'RANCHO CABILDO'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA FRANCISCO I. MADERO LA MESA'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA FRANCISCO VILLA TECOAC'],
            ['idMunicipio'=>2040,'nombre' =>'SAN FRANCISCO NOTARIO'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA ACASILLADOS SAN MARTIN NOTARIO'],
            ['idMunicipio'=>2040,'nombre' =>'COLONIA FRANCISCO I. MADERO TECOAC'],
            ['idMunicipio'=>2040,'nombre' =>'EL SUEÑO'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA MARGARITA'],
            ['idMunicipio'=>2040,'nombre' =>'EL MOLINO [RANCHERIA]'],
            ['idMunicipio'=>2040,'nombre' =>'AMPLIACION FELIPE CARRILLO PUERTO'],
            ['idMunicipio'=>2040,'nombre' =>'RANCHO MARICARMEN'],
            ['idMunicipio'=>2040,'nombre' =>'EL ROSARIO'],
            ['idMunicipio'=>2040,'nombre' =>'EJIDO YANCUITLALPAN'],
            ['idMunicipio'=>2040,'nombre' =>'FRACCION LA NATIVIDAD'],
            ['idMunicipio'=>2040,'nombre' =>'SAN DIEGO XALPATLAHUAYA'],
            ['idMunicipio'=>2040,'nombre' =>'CORNELIO MARQUEZ'],
            ['idMunicipio'=>2040,'nombre' =>'FRACCION SANTA ANA RIOS'],
            ['idMunicipio'=>2040,'nombre' =>'FRACCION XONECUILA (LAS PALMAS)'],
            ['idMunicipio'=>2040,'nombre' =>'ALEJANDRO AGUILAR'],
            ['idMunicipio'=>2040,'nombre' =>'SAN RAFAEL TEPATLAXCO EL BAJO'],
            ['idMunicipio'=>2040,'nombre' =>'LA CARRETA'],
            ['idMunicipio'=>2040,'nombre' =>'FRACCION SOLTEPEC (EL RINCON)'],
            ['idMunicipio'=>2040,'nombre' =>'MIGUEL ARIAS'],
            ['idMunicipio'=>2040,'nombre' =>'CHAPULTEPEC [GASOLINERA]'],
            ['idMunicipio'=>2040,'nombre' =>'ÁNGEL DE GABRIEL DE RAMON'],
            ['idMunicipio'=>2040,'nombre' =>'APOLINAR RODRIGUEZ'],
            ['idMunicipio'=>2040,'nombre' =>'LA CABAÑA'],
            ['idMunicipio'=>2040,'nombre' =>'ENRIQUE DE GABRIEL DE RAMON'],
            ['idMunicipio'=>2040,'nombre' =>'FRACCION DE XONECUILA'],
            ['idMunicipio'=>2040,'nombre' =>'EL PORVENIR'],
            ['idMunicipio'=>2040,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2040,'nombre' =>'LA PEDRERA'],
            ['idMunicipio'=>2040,'nombre' =>'LOS PINOS DOS'],
            ['idMunicipio'=>2040,'nombre' =>'LOS PINOS'],
            ['idMunicipio'=>2040,'nombre' =>'EL DURAZNO'],
            ['idMunicipio'=>2040,'nombre' =>'RANCHO ALEGRE'],
            ['idMunicipio'=>2040,'nombre' =>'EL REBOMBEO'],
            ['idMunicipio'=>2040,'nombre' =>'SAN CONSTANTINO'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA BARBARA'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA RITA'],
            ['idMunicipio'=>2040,'nombre' =>'SARITA DE LA MONTAÑA'],
            ['idMunicipio'=>2040,'nombre' =>'TIRSO GUTIERREZ'],
            ['idMunicipio'=>2040,'nombre' =>'TUBERA GUADALUPE'],
            ['idMunicipio'=>2040,'nombre' =>'LOS CERRITOS (HUERTA MARIA LUISA)'],
            ['idMunicipio'=>2040,'nombre' =>'JOSE DE JESUS SANCHEZ CARRILLO'],
            ['idMunicipio'=>2040,'nombre' =>'JOSE JUAN ROMERO LOPEZ'],
            ['idMunicipio'=>2040,'nombre' =>'LOS RAMALES'],
            ['idMunicipio'=>2040,'nombre' =>'SANTA LILIA'],
            ['idMunicipio'=>2040,'nombre' =>'EJIDO CUAUHTEMOC'],
            ['idMunicipio'=>2040,'nombre' =>'EL CRISTO (DON CARMELO)'],
            ['idMunicipio'=>2040,'nombre' =>'LA MESITA'],
            ['idMunicipio'=>2040,'nombre' =>'MARTIN SANTIAGO VAZQUEZ'],
            ['idMunicipio'=>2040,'nombre' =>'TRINIDAD ALTAMIRANO HERNANDEZ'],
            ['idMunicipio'=>2040,'nombre' =>'VICTOR LIMA (EL ESTABLITO)'],
            ['idMunicipio'=>2040,'nombre' =>'SAN MATEO [RANCHO]'],
            ['idMunicipio'=>2040,'nombre' =>'EJIDO ATENCO'],
            ['idMunicipio'=>2040,'nombre' =>'LA LOMA (JUAN FLORES)'],
            ['idMunicipio'=>2040,'nombre' =>'MARIANO TORRES'],
            ['idMunicipio'=>2041,'nombre' =>'HUEYOTLIPAN'],
            ['idMunicipio'=>2041,'nombre' =>'LA CRUZ TECHALOTE [COLONIA]'],
            ['idMunicipio'=>2041,'nombre' =>'IGNACIO ZARAGOZA'],
            ['idMunicipio'=>2041,'nombre' =>'SANTA MARIA IXCOTLA'],
            ['idMunicipio'=>2041,'nombre' =>'COLONIA ADOLFO LOPEZ MATEOS'],
            ['idMunicipio'=>2041,'nombre' =>'LA PURISIMA [RANCHO]'],
            ['idMunicipio'=>2041,'nombre' =>'SAN DIEGO RECOBA'],
            ['idMunicipio'=>2041,'nombre' =>'SAN ANDRES CUAXIMALA'],
            ['idMunicipio'=>2041,'nombre' =>'HACIENDA SAN BLAS CUAXOMULCO'],
            ['idMunicipio'=>2041,'nombre' =>'SAN FERNANDO'],
            ['idMunicipio'=>2041,'nombre' =>'SAN LORENZO TECHALOTE'],
            ['idMunicipio'=>2041,'nombre' =>'SAN MANUEL TLALPAN'],
            ['idMunicipio'=>2041,'nombre' =>'SAN SIMEON XIPETZINCO'],
            ['idMunicipio'=>2041,'nombre' =>'SANTIAGO TLALPAN'],
            ['idMunicipio'=>2041,'nombre' =>'EL CARMEN (LAS CARROZAS)'],
            ['idMunicipio'=>2041,'nombre' =>'AGUA LIMPIA'],
            ['idMunicipio'=>2041,'nombre' =>'NCP SAN ANTONIO TECHALOTE'],
            ['idMunicipio'=>2041,'nombre' =>'LOMA BONITA'],
            ['idMunicipio'=>2041,'nombre' =>'LAS TORTOLAS'],
            ['idMunicipio'=>2041,'nombre' =>'SANTA LUCIA'],
            ['idMunicipio'=>2041,'nombre' =>'EMILIO SANCHEZ PIEDRAS'],
            ['idMunicipio'=>2041,'nombre' =>'EL NOVILLO'],
            ['idMunicipio'=>2041,'nombre' =>'PLAYA AZUL'],
            ['idMunicipio'=>2041,'nombre' =>'LA CAÑADA'],
            ['idMunicipio'=>2041,'nombre' =>'ONESIMO FLORES ELIZALDE (EL CERRITO)'],
            ['idMunicipio'=>2041,'nombre' =>'LA PURISIMA'],
            ['idMunicipio'=>2041,'nombre' =>'RANCHO DE LAS MARIPOSAS'],
            ['idMunicipio'=>2041,'nombre' =>'LA ARDILLA'],
            ['idMunicipio'=>2041,'nombre' =>'LAS CRUCES'],
            ['idMunicipio'=>2041,'nombre' =>'FULGENCIO CONTRERAS SAAVEDRA'],
            ['idMunicipio'=>2041,'nombre' =>'SAN SEBASTIAN (TEOZOPILCO)'],
            ['idMunicipio'=>2041,'nombre' =>'CACHO GRANDE'],
            ['idMunicipio'=>2041,'nombre' =>'RINCON DEL VALLE (LAS CALAVERAS)'],
            ['idMunicipio'=>2041,'nombre' =>'LA LAGUNA'],
            ['idMunicipio'=>2041,'nombre' =>'POTRERO GRANDE'],
            ['idMunicipio'=>2041,'nombre' =>'ALEJANDRO CARRILLO'],
            ['idMunicipio'=>2042,'nombre' =>'VILLA MARIANO MATAMOROS'],
            ['idMunicipio'=>2042,'nombre' =>'ALPOTZONGA DE LIRA Y ORTEGA'],
            ['idMunicipio'=>2042,'nombre' =>'SAN ANTONIO ATOTONILCO'],
            ['idMunicipio'=>2042,'nombre' =>'LA CARIDAD CUAXONACAYO'],
            ['idMunicipio'=>2042,'nombre' =>'ESPIRITU SANTO'],
            ['idMunicipio'=>2042,'nombre' =>'GUADALUPE'],
            ['idMunicipio'=>2042,'nombre' =>'LA LADERA'],
            ['idMunicipio'=>2042,'nombre' =>'SAN JUAN NEPOPUALCO'],
            ['idMunicipio'=>2042,'nombre' =>'SAN GABRIEL POPOCATLA'],
            ['idMunicipio'=>2042,'nombre' =>'SAN ANTONIO TECOAC'],
            ['idMunicipio'=>2042,'nombre' =>'SAN ANTONIO TIZOSTOC'],
            ['idMunicipio'=>2042,'nombre' =>'SAN CRISTOBAL OXTOTLAPANGO'],
            ['idMunicipio'=>2042,'nombre' =>'SAN DIEGO XOCOYUCAN'],
            ['idMunicipio'=>2042,'nombre' =>'SAN MARCOS JILOTEPEC'],
            ['idMunicipio'=>2042,'nombre' =>'SAN MIGUEL LA PRESA'],
            ['idMunicipio'=>2042,'nombre' =>'SAN NICOLAS'],
            ['idMunicipio'=>2042,'nombre' =>'SANTA CRUZ EL PORVENIR'],
            ['idMunicipio'=>2042,'nombre' =>'SANTA INES TECUEXCOMAC'],
            ['idMunicipio'=>2042,'nombre' =>'SANTA JUSTINA ECATEPEC'],
            ['idMunicipio'=>2042,'nombre' =>'SANTA ROSA DE LIMA'],
            ['idMunicipio'=>2042,'nombre' =>'SANTIAGO XOCHIMILCO'],
            ['idMunicipio'=>2042,'nombre' =>'LA SOLEDAD'],
            ['idMunicipio'=>2042,'nombre' =>'LA TRINIDAD TENEXYECAC'],
            ['idMunicipio'=>2042,'nombre' =>'LA VIRGEN'],
            ['idMunicipio'=>2042,'nombre' =>'LAS HUERTAS'],
            ['idMunicipio'=>2042,'nombre' =>'SAN JOSE ESCANDONA'],
            ['idMunicipio'=>2042,'nombre' =>'ALPOTZONGA'],
            ['idMunicipio'=>2042,'nombre' =>'AGUSTIN LOPEZ'],
            ['idMunicipio'=>2042,'nombre' =>'RANCHO AYTEC (MONTE DE LOS OLIVOS)'],
            ['idMunicipio'=>2042,'nombre' =>'CAPULA'],
            ['idMunicipio'=>2042,'nombre' =>'SANTO DOMINGO'],
            ['idMunicipio'=>2042,'nombre' =>'EL CENTENARIO'],
            ['idMunicipio'=>2042,'nombre' =>'MIGUEL ÁNGEL [GRANJA]'],
            ['idMunicipio'=>2042,'nombre' =>'SAN RAFAEL [RANCHO]'],
            ['idMunicipio'=>2042,'nombre' =>'SAN LUCAS (EL JAGÜEY)'],
            ['idMunicipio'=>2042,'nombre' =>'SAN CARLOS'],
            ['idMunicipio'=>2042,'nombre' =>'GILDARDO RAMIREZ GONZALEZ'],
            ['idMunicipio'=>2042,'nombre' =>'LAS ROSITAS'],
            ['idMunicipio'=>2042,'nombre' =>'RANCHO MIRA EL SOL'],
            ['idMunicipio'=>2042,'nombre' =>'LAS MORAS (LAS MORADILLAS)'],
            ['idMunicipio'=>2042,'nombre' =>'FRACCION LA VIRGEN'],
            ['idMunicipio'=>2042,'nombre' =>'SAN LUCAS'],
            ['idMunicipio'=>2042,'nombre' =>'LA FISCALA'],
            ['idMunicipio'=>2042,'nombre' =>'EL PASO DEL NORTE'],
            ['idMunicipio'=>2042,'nombre' =>'COLONIA EJIDO SANTA JUSTINA ECATEPEC'],
            ['idMunicipio'=>2042,'nombre' =>'SAN LUCAS (EL CAMPIRANO)'],
            ['idMunicipio'=>2042,'nombre' =>'TEZOQUIPAN'],
            ['idMunicipio'=>2042,'nombre' =>'LA HUERFANA'],
            ['idMunicipio'=>2042,'nombre' =>'LEONARDO NAJERA DIAZ'],
            ['idMunicipio'=>2042,'nombre' =>'RANCHO DE LA VIRGEN'],
            ['idMunicipio'=>2042,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2042,'nombre' =>'EL MORAL'],
            ['idMunicipio'=>2042,'nombre' =>'JAVIER PULIDO'],
            ['idMunicipio'=>2042,'nombre' =>'EL REFUGIO'],
            ['idMunicipio'=>2042,'nombre' =>'TLALOC'],
            ['idMunicipio'=>2042,'nombre' =>'TLALPIZACO'],
            ['idMunicipio'=>2042,'nombre' =>'CANDILUZ MACIAS'],
            ['idMunicipio'=>2042,'nombre' =>'LAS TORRES'],
            ['idMunicipio'=>2042,'nombre' =>'RANCHO ESCONDIDO'],
            ['idMunicipio'=>2042,'nombre' =>'SAN FRANCISCO [COLONIA]'],
            ['idMunicipio'=>2042,'nombre' =>'EL RETORNO [RANCHO]'],
            ['idMunicipio'=>2042,'nombre' =>'FRANK CERVANTES'],
            ['idMunicipio'=>2042,'nombre' =>'LA LAGUNA'],
            ['idMunicipio'=>2042,'nombre' =>'EL RANCHITO'],
            ['idMunicipio'=>2042,'nombre' =>'LA VENTA'],
            ['idMunicipio'=>2043,'nombre' =>'IXTENCO'],
            ['idMunicipio'=>2043,'nombre' =>'BARRIO DE RESURRECCION SEGUNDO'],
            ['idMunicipio'=>2043,'nombre' =>'LOS ÁLAMOS'],
            ['idMunicipio'=>2043,'nombre' =>'LOS PILARES'],
            ['idMunicipio'=>2043,'nombre' =>'LA ERA'],
            ['idMunicipio'=>2043,'nombre' =>'MIGUEL MUÑOZ LEON'],
            ['idMunicipio'=>2043,'nombre' =>'PEDRO HUERTA GUTIERREZ (EL CRISTO)'],
            ['idMunicipio'=>2043,'nombre' =>'DARIO BIXANO GASPAR'],
            ['idMunicipio'=>2043,'nombre' =>'EDUARDO MONTES'],
            ['idMunicipio'=>2043,'nombre' =>'FELIPE TELLEZ (BARRANCA EL CALVARIO)'],
            ['idMunicipio'=>2044,'nombre' =>'MAZATECOCHCO'],
            ['idMunicipio'=>2044,'nombre' =>'COLOZITZI'],
            ['idMunicipio'=>2044,'nombre' =>'ZACATECOMA'],
            ['idMunicipio'=>2044,'nombre' =>'ÁLAMO'],
            ['idMunicipio'=>2044,'nombre' =>'SAN JUAN IXHUALCO'],
            ['idMunicipio'=>2045,'nombre' =>'CONTLA'],
            ['idMunicipio'=>2045,'nombre' =>'SAN FELIPE CUAUHTENCO'],
            ['idMunicipio'=>2045,'nombre' =>'IXTLAHUACA'],
            ['idMunicipio'=>2045,'nombre' =>'SAN JOSE AZTATLA'],
            ['idMunicipio'=>2045,'nombre' =>'SANTA MARIA AQUIAHUAC'],
            ['idMunicipio'=>2045,'nombre' =>'LA LUZ [BARRIO]'],
            ['idMunicipio'=>2045,'nombre' =>'OCOTLAN TEPATLAXCO'],
            ['idMunicipio'=>2045,'nombre' =>'CAPULA'],
            ['idMunicipio'=>2045,'nombre' =>'ATLAPECHCO'],
            ['idMunicipio'=>2045,'nombre' =>'RANCHO HUEYICUENTLA'],
            ['idMunicipio'=>2046,'nombre' =>'TEPETITLA'],
            ['idMunicipio'=>2046,'nombre' =>'GUADALUPE VICTORIA'],
            ['idMunicipio'=>2046,'nombre' =>'SAN MATEO AYECAC'],
            ['idMunicipio'=>2046,'nombre' =>'VILLA ALTA'],
            ['idMunicipio'=>2046,'nombre' =>'SANTA ROSA'],
            ['idMunicipio'=>2046,'nombre' =>'LOS MORELIA'],
            ['idMunicipio'=>2046,'nombre' =>'SAN JUAN MOLINO'],
            ['idMunicipio'=>2046,'nombre' =>'TLALMECATE'],
            ['idMunicipio'=>2046,'nombre' =>'CANAL SAN LUCAS'],
            ['idMunicipio'=>2046,'nombre' =>'PORCICOLA JALISCO'],
            ['idMunicipio'=>2046,'nombre' =>'PUERTA (CABIÑO)'],
            ['idMunicipio'=>2046,'nombre' =>'EL CAMBIO'],
            ['idMunicipio'=>2046,'nombre' =>'ROQUE RIVERA PALAFOX'],
            ['idMunicipio'=>2046,'nombre' =>'SAN JOAQUIN'],
            ['idMunicipio'=>2046,'nombre' =>'NIXTLALPAN'],
            ['idMunicipio'=>2046,'nombre' =>'LOS AMEYALES (LA JOYITA)'],
            ['idMunicipio'=>2047,'nombre' =>'SANCTORUM'],
            ['idMunicipio'=>2047,'nombre' =>'ESTACION CONTADERO'],
            ['idMunicipio'=>2047,'nombre' =>'FRANCISCO VILLA'],
            ['idMunicipio'=>2047,'nombre' =>'LA PROVIDENCIA'],
            ['idMunicipio'=>2047,'nombre' =>'SAN NICOLAS EL GRANDE'],
            ['idMunicipio'=>2047,'nombre' =>'LOS ALPINOS'],
            ['idMunicipio'=>2047,'nombre' =>'ESQUIBAJAS'],
            ['idMunicipio'=>2047,'nombre' =>'LA ESPERANZA'],
            ['idMunicipio'=>2047,'nombre' =>'SANTA CRUZ'],
            ['idMunicipio'=>2047,'nombre' =>'SAN LEONARDO ARROYO'],
            ['idMunicipio'=>2047,'nombre' =>'LA LADERA'],
            ['idMunicipio'=>2047,'nombre' =>'LA PRESA DE POZUELOS'],
            ['idMunicipio'=>2047,'nombre' =>'SAN NICOLAS (FARFAN)'],
            ['idMunicipio'=>2047,'nombre' =>'JUAN ANTONIO'],
            ['idMunicipio'=>2047,'nombre' =>'NCP ÁLVARO OBREGON'],
            ['idMunicipio'=>2047,'nombre' =>'JULIO ROLDAN'],
            ['idMunicipio'=>2047,'nombre' =>'LAS PALOMAS'],
            ['idMunicipio'=>2047,'nombre' =>'DOÑA EVELIA (LOS ALPINOS)'],
            ['idMunicipio'=>2047,'nombre' =>'RANCHO PACHUQUILLA'],
            ['idMunicipio'=>2047,'nombre' =>'CELIA PEREZ'],
            ['idMunicipio'=>2048,'nombre' =>'CIUDAD DE NANACAMILPA'],
            ['idMunicipio'=>2048,'nombre' =>'CRUZ BLANCA'],
            ['idMunicipio'=>2048,'nombre' =>'DOMINGO ARENAS (LA CALERA)'],
            ['idMunicipio'=>2048,'nombre' =>'FRANCISCO I. MADERO'],
            ['idMunicipio'=>2048,'nombre' =>'IXTAFIAYUCA'],
            ['idMunicipio'=>2048,'nombre' =>'MIGUEL LIRA Y ORTEGA'],
            ['idMunicipio'=>2048,'nombre' =>'SAN CAYETANO'],
            ['idMunicipio'=>2048,'nombre' =>'SAN FELIPE HIDALGO'],
            ['idMunicipio'=>2048,'nombre' =>'SAN ISIDRO'],
            ['idMunicipio'=>2048,'nombre' =>'COLONIA TEPUENTE'],
            ['idMunicipio'=>2048,'nombre' =>'EL CARMEN [RANCHO]'],
            ['idMunicipio'=>2048,'nombre' =>'RANCHO TEBARROSO (EL CAPITAN)'],
            ['idMunicipio'=>2048,'nombre' =>'CAJA DE AGUA'],
            ['idMunicipio'=>2048,'nombre' =>'LOS MANUELES'],
            ['idMunicipio'=>2048,'nombre' =>'LOS ROSALES'],
            ['idMunicipio'=>2048,'nombre' =>'LOS DELGADILLO'],
            ['idMunicipio'=>2048,'nombre' =>'JAGÜEY SECO'],
            ['idMunicipio'=>2048,'nombre' =>'MIFIVE'],
            ['idMunicipio'=>2048,'nombre' =>'AGUA ESCONDIDA'],
            ['idMunicipio'=>2048,'nombre' =>'EL TULAR'],
            ['idMunicipio'=>2048,'nombre' =>'LAS BUGAMBILIAS'],
            ['idMunicipio'=>2048,'nombre' =>'EL CAPULIN'],
            ['idMunicipio'=>2048,'nombre' =>'LOS CEIBOS'],
            ['idMunicipio'=>2048,'nombre' =>'LAS MARAVILLAS'],
            ['idMunicipio'=>2048,'nombre' =>'SAN PEDRO [RANCHO]'],
            ['idMunicipio'=>2048,'nombre' =>'LA LOMA DE ENMEDIO (AXOCOPA)'],
            ['idMunicipio'=>2048,'nombre' =>'ADRIAN HERNANDEZ'],
            ['idMunicipio'=>2048,'nombre' =>'ÁNGELA GARCIA'],
            ['idMunicipio'=>2048,'nombre' =>'ENTRONQUE NANACAMILPA'],
            ['idMunicipio'=>2048,'nombre' =>'JUAN LEON'],
            ['idMunicipio'=>2048,'nombre' =>'TEBARROSO'],
            ['idMunicipio'=>2048,'nombre' =>'LAS MANZANAS'],
            ['idMunicipio'=>2048,'nombre' =>'LA LOMA DE MAZAPA'],
            ['idMunicipio'=>2048,'nombre' =>'PUEBLO NUEVO'],
            ['idMunicipio'=>2048,'nombre' =>'SANTOS LOZANO'],
            ['idMunicipio'=>2048,'nombre' =>'LOS COLGADOS'],
            ['idMunicipio'=>2048,'nombre' =>'ALEJANDRO CARRASCO'],
            ['idMunicipio'=>2048,'nombre' =>'EL CIPRES'],
            ['idMunicipio'=>2048,'nombre' =>'AXOCOPA'],
            ['idMunicipio'=>2048,'nombre' =>'LOS PAREDONES'],
            ['idMunicipio'=>2048,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2048,'nombre' =>'PRESA DE POZUELOS'],
            ['idMunicipio'=>2048,'nombre' =>'EL ALCANFOR [RANCHO]'],
            ['idMunicipio'=>2048,'nombre' =>'SAN MARCOS [RANCHO]'],
            ['idMunicipio'=>2049,'nombre' =>'ACUAMANALA'],
            ['idMunicipio'=>2049,'nombre' =>'CONCEPCION CHIMALPA'],
            ['idMunicipio'=>2049,'nombre' =>'GUADALUPE HIDALGO'],
            ['idMunicipio'=>2049,'nombre' =>'OLEXTLA DE JUAREZ'],
            ['idMunicipio'=>2050,'nombre' =>'NATIVITAS'],
            ['idMunicipio'=>2050,'nombre' =>'SAN MIGUEL ANALCO'],
            ['idMunicipio'=>2050,'nombre' =>'SAN BERNABE CAPULA'],
            ['idMunicipio'=>2050,'nombre' =>'SANTO TOMAS LA CONCORDIA'],
            ['idMunicipio'=>2050,'nombre' =>'GUADALUPE VICTORIA'],
            ['idMunicipio'=>2050,'nombre' =>'JESUS TEPACTEPEC'],
            ['idMunicipio'=>2050,'nombre' =>'SAN ANTONIO TEACALCO'],
            ['idMunicipio'=>2050,'nombre' =>'SAN JOSE ATOYATENCO'],
            ['idMunicipio'=>2050,'nombre' =>'SAN MIGUEL DEL MILAGRO'],
            ['idMunicipio'=>2050,'nombre' =>'SAN MIGUEL XOCHITECATITLA'],
            ['idMunicipio'=>2050,'nombre' =>'SAN RAFAEL TENANYECAC'],
            ['idMunicipio'=>2050,'nombre' =>'SANTA CLARA ATOYAC'],
            ['idMunicipio'=>2050,'nombre' =>'SANTIAGO MICHAC'],
            ['idMunicipio'=>2050,'nombre' =>'SAN VICENTE XILOXOCHITLA'],
            ['idMunicipio'=>2050,'nombre' =>'SAN FRANCISCO TENEXYECAC'],
            ['idMunicipio'=>2050,'nombre' =>'SAN JUAN TEPACTEPEC'],
            ['idMunicipio'=>2050,'nombre' =>'SAN MIGUEL TLALE'],
            ['idMunicipio'=>2050,'nombre' =>'EX-HACIENDA SANTA ELENA'],
            ['idMunicipio'=>2050,'nombre' =>'MIGUEL SALOMA'],
            ['idMunicipio'=>2050,'nombre' =>'SAN ANTONIO'],
            ['idMunicipio'=>2050,'nombre' =>'LOMA VERDE'],
            ['idMunicipio'=>2050,'nombre' =>'EL ROSARIO [RANCHO]'],
            ['idMunicipio'=>2050,'nombre' =>'MATAMOROS'],
            ['idMunicipio'=>2050,'nombre' =>'RUTILO VAZQUEZ'],
            ['idMunicipio'=>2050,'nombre' =>'NCP SANTA ELENA TEACALCO'],
            ['idMunicipio'=>2050,'nombre' =>'ZANJA REAL'],
            ['idMunicipio'=>2050,'nombre' =>'COLECTURIA'],
            ['idMunicipio'=>2050,'nombre' =>'CRISTO REY'],
            ['idMunicipio'=>2050,'nombre' =>'PIEDRA BLANCA'],
            ['idMunicipio'=>2050,'nombre' =>'EL RANCHO'],
            ['idMunicipio'=>2050,'nombre' =>'LA CABAÑA'],
            ['idMunicipio'=>2050,'nombre' =>'JARDINES DE TEPACTEPEC'],
            ['idMunicipio'=>2050,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2050,'nombre' =>'LA ZANJA'],
            ['idMunicipio'=>2051,'nombre' =>'PANOTLA'],
            ['idMunicipio'=>2051,'nombre' =>'JESUS ACATITLA'],
            ['idMunicipio'=>2051,'nombre' =>'SAN AMBROSIO TEXANTLA'],
            ['idMunicipio'=>2051,'nombre' =>'SAN FRANCISCO TEMETZONTLA'],
            ['idMunicipio'=>2051,'nombre' =>'SAN JORGE TEZOQUIPAN'],
            ['idMunicipio'=>2051,'nombre' =>'SAN MATEO HUEXOYUCAN'],
            ['idMunicipio'=>2051,'nombre' =>'SANTA CATALINA APATLAHCO'],
            ['idMunicipio'=>2051,'nombre' =>'SANTA CRUZ TECHACHALCO'],
            ['idMunicipio'=>2051,'nombre' =>'SAN TADEO HUILOAPAN'],
            ['idMunicipio'=>2051,'nombre' =>'BARRIO DEL MORAL'],
            ['idMunicipio'=>2051,'nombre' =>'NIXTLALPA'],
            ['idMunicipio'=>2051,'nombre' =>'EL NOPAL'],
            ['idMunicipio'=>2051,'nombre' =>'LA PLANA (LOS VOLCANES)'],
            ['idMunicipio'=>2051,'nombre' =>'LA CIENEGA'],
            ['idMunicipio'=>2051,'nombre' =>'CHICHIAPAS'],
            ['idMunicipio'=>2051,'nombre' =>'FRACCIONAMIENTO LA VIRGEN'],
            ['idMunicipio'=>2051,'nombre' =>'LA HACIENDA VIEJA'],
            ['idMunicipio'=>2051,'nombre' =>'CAMINO A SAN MIGUEL'],
            ['idMunicipio'=>2051,'nombre' =>'FRACCIONAMIENTO SANTA ELENA'],
            ['idMunicipio'=>2051,'nombre' =>'UNIDAD HABITACIONAL II'],
            ['idMunicipio'=>2051,'nombre' =>'TLATENCO'],
            ['idMunicipio'=>2052,'nombre' =>'VILLA VICENTE GUERRERO'],
            ['idMunicipio'=>2052,'nombre' =>'SAN ISIDRO BUEN SUCESO'],
            ['idMunicipio'=>2052,'nombre' =>'EX-HACIENDA GUADALUPE XALTELULCO'],
            ['idMunicipio'=>2052,'nombre' =>'ACOPILCO'],
            ['idMunicipio'=>2052,'nombre' =>'AHUASHUAME'],
            ['idMunicipio'=>2052,'nombre' =>'TETZACUAL'],
            ['idMunicipio'=>2052,'nombre' =>'XOYACOLOTZI'],
            ['idMunicipio'=>2052,'nombre' =>'XAHUEN VARGAS'],
            ['idMunicipio'=>2052,'nombre' =>'PIPILATZI'],
            ['idMunicipio'=>2052,'nombre' =>'SAN ISIDROSO (COYOTERA)'],
            ['idMunicipio'=>2052,'nombre' =>'PATLAGUACTETL'],
            ['idMunicipio'=>2052,'nombre' =>'POPOZOTZI'],
            ['idMunicipio'=>2052,'nombre' =>'HUEYOCOTL'],
            ['idMunicipio'=>2052,'nombre' =>'ARCOTITLA'],
            ['idMunicipio'=>2052,'nombre' =>'CACAMILA SAN ANTONIO'],
            ['idMunicipio'=>2052,'nombre' =>'CALAQUIOTLI'],
            ['idMunicipio'=>2052,'nombre' =>'CUENTENTZINCO'],
            ['idMunicipio'=>2052,'nombre' =>'MULATLA'],
            ['idMunicipio'=>2052,'nombre' =>'OCOILACAS'],
            ['idMunicipio'=>2052,'nombre' =>'SAN JOSE TECOSAHUATLA'],
            ['idMunicipio'=>2052,'nombre' =>'XAHUENTEPIZILA'],
            ['idMunicipio'=>2052,'nombre' =>'JUQUILA'],
            ['idMunicipio'=>2052,'nombre' =>'PERESTLALI'],
            ['idMunicipio'=>2052,'nombre' =>'TLAPITZAC'],
            ['idMunicipio'=>2052,'nombre' =>'HUEYPRESA'],
            ['idMunicipio'=>2052,'nombre' =>'HUEYRASTRUJO'],
            ['idMunicipio'=>2052,'nombre' =>'LLEPAZOTLA'],
            ['idMunicipio'=>2052,'nombre' =>'MOXONTITLA'],
            ['idMunicipio'=>2052,'nombre' =>'PAPANASNO'],
            ['idMunicipio'=>2052,'nombre' =>'PILAZOL'],
            ['idMunicipio'=>2052,'nombre' =>'SAIS'],
            ['idMunicipio'=>2052,'nombre' =>'TECAMACHAL'],
            ['idMunicipio'=>2052,'nombre' =>'TEPECHIHUATL'],
            ['idMunicipio'=>2052,'nombre' =>'XAHUENTLATEMPA'],
            ['idMunicipio'=>2053,'nombre' =>'SANTA CRUZ TLAXCALA'],
            ['idMunicipio'=>2053,'nombre' =>'GUADALUPE TLACHCO'],
            ['idMunicipio'=>2053,'nombre' =>'JESUS HUITZNAHUAC'],
            ['idMunicipio'=>2053,'nombre' =>'SAN LUCAS TLACOCHCALCO'],
            ['idMunicipio'=>2053,'nombre' =>'SAN MIGUEL CONTLA'],
            ['idMunicipio'=>2053,'nombre' =>'COLONIA PROGRESO'],
            ['idMunicipio'=>2053,'nombre' =>'XAMISTLA'],
            ['idMunicipio'=>2053,'nombre' =>'ALEJANDRO PEÑA CONDE'],
            ['idMunicipio'=>2053,'nombre' =>'TETZOTZOCOLA'],
            ['idMunicipio'=>2053,'nombre' =>'POTRERO VIEJO'],
            ['idMunicipio'=>2053,'nombre' =>'EL TESORO (BAUTISTA) [RANCHO]'],
            ['idMunicipio'=>2053,'nombre' =>'CUYOACO'],
            ['idMunicipio'=>2053,'nombre' =>'COXTLA'],
            ['idMunicipio'=>2053,'nombre' =>'SAN LORENZO XALTELULCO'],
            ['idMunicipio'=>2054,'nombre' =>'TENANCINGO'],
            ['idMunicipio'=>2054,'nombre' =>'CONCEPCION ACOPILCO'],
            ['idMunicipio'=>2054,'nombre' =>'EL PUENTE'],
            ['idMunicipio'=>2054,'nombre' =>'TEPEPANTLALPA (MAGDALENA REYES)'],
            ['idMunicipio'=>2054,'nombre' =>'LA RENDA'],
            ['idMunicipio'=>2054,'nombre' =>'TECOAC'],
            ['idMunicipio'=>2055,'nombre' =>'TEOLOCHOLCO'],
            ['idMunicipio'=>2055,'nombre' =>'EL CARMEN AZTAMA'],
            ['idMunicipio'=>2055,'nombre' =>'ACXOTLA DEL MONTE'],
            ['idMunicipio'=>2055,'nombre' =>'CUAXINCA'],
            ['idMunicipio'=>2055,'nombre' =>'POPOZOTZI'],
            ['idMunicipio'=>2055,'nombre' =>'AYOCALCO'],
            ['idMunicipio'=>2055,'nombre' =>'LOMA DE HUEYHUEYITECOX'],
            ['idMunicipio'=>2055,'nombre' =>'LA VUELTA'],
            ['idMunicipio'=>2055,'nombre' =>'TEXALEPILA'],
            ['idMunicipio'=>2055,'nombre' =>'ZACAZONTETLA'],
            ['idMunicipio'=>2055,'nombre' =>'ZAPAHUA'],
            ['idMunicipio'=>2055,'nombre' =>'ALAILAZOTL'],
            ['idMunicipio'=>2055,'nombre' =>'TEPOCHMETLATL'],
            ['idMunicipio'=>2055,'nombre' =>'TEPIZILA'],
            ['idMunicipio'=>2055,'nombre' =>'APACHCO'],
            ['idMunicipio'=>2055,'nombre' =>'CUACHEXTLAN'],
            ['idMunicipio'=>2055,'nombre' =>'COACOCOXTLA'],
            ['idMunicipio'=>2055,'nombre' =>'ROMAN ZITLALPOPOCATL'],
            ['idMunicipio'=>2055,'nombre' =>'TEPETUMAYO'],
            ['idMunicipio'=>2056,'nombre' =>'TEPEYANCO'],
            ['idMunicipio'=>2056,'nombre' =>'LAS ÁGUILAS [COLONIA]'],
            ['idMunicipio'=>2056,'nombre' =>'SAN COSME ATLAMAXAC'],
            ['idMunicipio'=>2056,'nombre' =>'LA AURORA'],
            ['idMunicipio'=>2056,'nombre' =>'COLONIA GUERRERO'],
            ['idMunicipio'=>2056,'nombre' =>'SANTIAGO TLACOCHCALCO'],
            ['idMunicipio'=>2056,'nombre' =>'SAN PEDRO XALCALTZINCO'],
            ['idMunicipio'=>2056,'nombre' =>'ARMANDO SANCHEZ'],
            ['idMunicipio'=>2056,'nombre' =>'GERARDO FRANCO'],
            ['idMunicipio'=>2056,'nombre' =>'ANTORCHA CAMPESINA'],
            ['idMunicipio'=>2056,'nombre' =>'COLONIA GUADALUPE'],
            ['idMunicipio'=>2056,'nombre' =>'EL POTRERO'],
            ['idMunicipio'=>2057,'nombre' =>'TERRENATE'],
            ['idMunicipio'=>2057,'nombre' =>'LOS AMELES (ACOLCO)'],
            ['idMunicipio'=>2057,'nombre' =>'EL CAPULIN [COLONIA]'],
            ['idMunicipio'=>2057,'nombre' =>'EL CAPULIN [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'CERRITO DE GUADALUPE'],
            ['idMunicipio'=>2057,'nombre' =>'CORTESCO'],
            ['idMunicipio'=>2057,'nombre' =>'GUADALUPE VICTORIA'],
            ['idMunicipio'=>2057,'nombre' =>'EL PILANCON'],
            ['idMunicipio'=>2057,'nombre' =>'EL RINCON [RANCHERIA]'],
            ['idMunicipio'=>2057,'nombre' =>'LA ROSA [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'NICOLAS BRAVO'],
            ['idMunicipio'=>2057,'nombre' =>'SAN JOSE VILLARREAL'],
            ['idMunicipio'=>2057,'nombre' =>'TENEXAC'],
            ['idMunicipio'=>2057,'nombre' =>'RANCHO TEPEYAHUALCO'],
            ['idMunicipio'=>2057,'nombre' =>'TOLUCA DE GUADALUPE'],
            ['idMunicipio'=>2057,'nombre' =>'COMUNIDAD CUATRO CAMINOS (EL ROSARIO)'],
            ['idMunicipio'=>2057,'nombre' =>'LA MESA (LA CUMBRE) [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'LA PRESA [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'SAN JUAN VILLARREAL [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'SANTA ANA [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'RANCHO VIEJO'],
            ['idMunicipio'=>2057,'nombre' =>'LA CANDELARIA [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'SAN PEDRO DE GUADALUPE'],
            ['idMunicipio'=>2057,'nombre' =>'RANCHO PUERTA COLORADA'],
            ['idMunicipio'=>2057,'nombre' =>'SAN MIGUEL [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'LOS AMELES [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'SAN ISIDRO [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'RANCHO GUADALUPE'],
            ['idMunicipio'=>2057,'nombre' =>'LA PERA'],
            ['idMunicipio'=>2057,'nombre' =>'EL DORADO [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'EL OCOTE (LAS POZAS) [RANCHO]'],
            ['idMunicipio'=>2057,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2057,'nombre' =>'LA CALDERA'],
            ['idMunicipio'=>2057,'nombre' =>'CRISTALACO'],
            ['idMunicipio'=>2057,'nombre' =>'JOSE MELQUIADES HERNANDEZ ALTAMIRANO (RANCHO EL BARRIL)'],
            ['idMunicipio'=>2057,'nombre' =>'MALLORICO DE FERMIN ALTAMIRANO (EL PARAISO)'],
            ['idMunicipio'=>2057,'nombre' =>'PASO HONDO'],
            ['idMunicipio'=>2057,'nombre' =>'SABAS DE FERMIN ALTAMIRANO (LA CAÑADA)'],
            ['idMunicipio'=>2058,'nombre' =>'TETLA'],
            ['idMunicipio'=>2058,'nombre' =>'CAPULAC'],
            ['idMunicipio'=>2058,'nombre' =>'SAN BARTOLOME MATLALOHCAN'],
            ['idMunicipio'=>2058,'nombre' =>'SAN FRANCISCO ATEXCATZINCO'],
            ['idMunicipio'=>2058,'nombre' =>'SAN JOSE PIEDRAS NEGRAS'],
            ['idMunicipio'=>2058,'nombre' =>'SANTA FE LA TROJE'],
            ['idMunicipio'=>2058,'nombre' =>'JOSE MARIA MORELOS Y PAVON'],
            ['idMunicipio'=>2058,'nombre' =>'PLAN DE AYALA'],
            ['idMunicipio'=>2058,'nombre' =>'EL PRADO'],
            ['idMunicipio'=>2058,'nombre' =>'SAN ISIDRO PIEDRAS NEGRAS'],
            ['idMunicipio'=>2058,'nombre' =>'SANTA ROSA MENA [COLONIA]'],
            ['idMunicipio'=>2058,'nombre' =>'SAN GREGORIO'],
            ['idMunicipio'=>2058,'nombre' =>'SAN ISIDRO'],
            ['idMunicipio'=>2058,'nombre' =>'SANTA MARGARITA'],
            ['idMunicipio'=>2058,'nombre' =>'XOMETLA'],
            ['idMunicipio'=>2058,'nombre' =>'EL POZO [RANCHO]'],
            ['idMunicipio'=>2058,'nombre' =>'RICARDO FLORES MAGON'],
            ['idMunicipio'=>2058,'nombre' =>'LA CONCEPCION'],
            ['idMunicipio'=>2058,'nombre' =>'DON RUFINO'],
            ['idMunicipio'=>2058,'nombre' =>'JUAN LIMA OLIVARES'],
            ['idMunicipio'=>2058,'nombre' =>'RANCHO FELIPE MACIAS'],
            ['idMunicipio'=>2058,'nombre' =>'LAS ARENAS'],
            ['idMunicipio'=>2058,'nombre' =>'EL CORAZON'],
            ['idMunicipio'=>2058,'nombre' =>'EJIDO DE APIZAQUITO'],
            ['idMunicipio'=>2058,'nombre' =>'FRACCION EL DERRAMADERO'],
            ['idMunicipio'=>2058,'nombre' =>'RANCHO DE GOMEZ'],
            ['idMunicipio'=>2058,'nombre' =>'NCPE SAN FRANCISCO TEPEYANCO'],
            ['idMunicipio'=>2058,'nombre' =>'SAN MIGUEL [RANCHO]'],
            ['idMunicipio'=>2058,'nombre' =>'ALEJANDRO LOPEZ ÁVILA (LOS TEMONTONES)'],
            ['idMunicipio'=>2058,'nombre' =>'LA AVENIDA'],
            ['idMunicipio'=>2058,'nombre' =>'LAS CABAÑAS'],
            ['idMunicipio'=>2058,'nombre' =>'ALVARADO [CARTONERA]'],
            ['idMunicipio'=>2058,'nombre' =>'JUAN ANTONIO GALVEZ [CARTONERA]'],
            ['idMunicipio'=>2058,'nombre' =>'DON JORGE'],
            ['idMunicipio'=>2058,'nombre' =>'FELIPE GUTIERREZ'],
            ['idMunicipio'=>2058,'nombre' =>'GUILLERMO MACIAS'],
            ['idMunicipio'=>2058,'nombre' =>'LA CARIDAD'],
            ['idMunicipio'=>2058,'nombre' =>'LA DIVINA PROVIDENCIA'],
            ['idMunicipio'=>2058,'nombre' =>'SAN JUAN'],
            ['idMunicipio'=>2058,'nombre' =>'EL CAZADOR'],
            ['idMunicipio'=>2058,'nombre' =>'SAN JUDAS TADEO'],
            ['idMunicipio'=>2058,'nombre' =>'RICARDO AGUIRRE MARTINEZ [CARTONERA]'],
            ['idMunicipio'=>2058,'nombre' =>'EL PEDREGAL [RANCHO]'],
            ['idMunicipio'=>2058,'nombre' =>'LA CABAÑA DEL INDIO [RANCHO]'],
            ['idMunicipio'=>2058,'nombre' =>'RANCHO ROMAN MORALES'],
            ['idMunicipio'=>2059,'nombre' =>'TETLATLAHUCA'],
            ['idMunicipio'=>2059,'nombre' =>'SAN ANDRES CUAMILPA'],
            ['idMunicipio'=>2059,'nombre' =>'SAN BARTOLOME TENANGO'],
            ['idMunicipio'=>2059,'nombre' =>'SANTA ANA PORTALES'],
            ['idMunicipio'=>2059,'nombre' =>'SANTA CRUZ AQUIAHUAC'],
            ['idMunicipio'=>2059,'nombre' =>'SANTA CRUZ CAPULINARES'],
            ['idMunicipio'=>2059,'nombre' =>'GUETULIO SUAREZ LOPEZ'],
            ['idMunicipio'=>2059,'nombre' =>'LICONSA (LA REGADERA)'],
            ['idMunicipio'=>2059,'nombre' =>'ATENCO'],
            ['idMunicipio'=>2059,'nombre' =>'PAREDON'],
            ['idMunicipio'=>2059,'nombre' =>'EL POTRERO'],
            ['idMunicipio'=>2059,'nombre' =>'LA CACHORRA'],
            ['idMunicipio'=>2059,'nombre' =>'ZAVALETA'],
            ['idMunicipio'=>2059,'nombre' =>'PISCILA'],
            ['idMunicipio'=>2059,'nombre' =>'RINCONADA'],
            ['idMunicipio'=>2059,'nombre' =>'SANTA ÁGUEDA'],
            ['idMunicipio'=>2059,'nombre' =>'EL COLUMPIO'],
            ['idMunicipio'=>2059,'nombre' =>'EL FRESNO'],
            ['idMunicipio'=>2059,'nombre' =>'LAS MESAS'],
            ['idMunicipio'=>2059,'nombre' =>'LOS PINOS'],
            ['idMunicipio'=>2060,'nombre' =>'TLAXCALA DE XICOHTENCATL'],
            ['idMunicipio'=>2060,'nombre' =>'OCOTLAN'],
            ['idMunicipio'=>2060,'nombre' =>'SAN BUENAVENTURA ATEMPAN'],
            ['idMunicipio'=>2060,'nombre' =>'SAN DIEGO METEPEC'],
            ['idMunicipio'=>2060,'nombre' =>'SAN ESTEBAN TIZATLAN'],
            ['idMunicipio'=>2060,'nombre' =>'SAN GABRIEL CUAUHTLA'],
            ['idMunicipio'=>2060,'nombre' =>'SAN HIPOLITO CHIMALPA'],
            ['idMunicipio'=>2060,'nombre' =>'SAN LUCAS CUAUHTELULPAN'],
            ['idMunicipio'=>2060,'nombre' =>'SAN SEBASTIAN ATLAHAPA'],
            ['idMunicipio'=>2060,'nombre' =>'SANTA MARIA ACUITLAPILCO'],
            ['idMunicipio'=>2060,'nombre' =>'SANTA MARIA IXTULCO'],
            ['idMunicipio'=>2060,'nombre' =>'LA TRINIDAD TEPEHITEC'],
            ['idMunicipio'=>2060,'nombre' =>'LA ERA'],
            ['idMunicipio'=>2060,'nombre' =>'CRUZ BLANCA'],
            ['idMunicipio'=>2060,'nombre' =>'POTRERO GRANDE'],
            ['idMunicipio'=>2060,'nombre' =>'RANCHO CRUZ BLANCA (SAN ISIDRO)'],
            ['idMunicipio'=>2061,'nombre' =>'TLAXCO'],
            ['idMunicipio'=>2061,'nombre' =>'ACOPINALCO DEL PEÑON'],
            ['idMunicipio'=>2061,'nombre' =>'EX-HACIENDA SAN MIGUEL MIMIAHUAPAN'],
            ['idMunicipio'=>2061,'nombre' =>'SAN JOSE ATOTONILCO'],
            ['idMunicipio'=>2061,'nombre' =>'LA CANDELARIA'],
            ['idMunicipio'=>2061,'nombre' =>'CAPILLA DE TEPEYAHUALCO'],
            ['idMunicipio'=>2061,'nombre' =>'LOS CAPULINES'],
            ['idMunicipio'=>2061,'nombre' =>'CASA BLANCA'],
            ['idMunicipio'=>2061,'nombre' =>'LA CIENEGA'],
            ['idMunicipio'=>2061,'nombre' =>'CONZOQUIO'],
            ['idMunicipio'=>2061,'nombre' =>'EL CONVENTO'],
            ['idMunicipio'=>2061,'nombre' =>'CORRALILLOS'],
            ['idMunicipio'=>2061,'nombre' =>'LOS CHARCOS'],
            ['idMunicipio'=>2061,'nombre' =>'SAN ANTONIO CHAPULTEPEC'],
            ['idMunicipio'=>2061,'nombre' =>'ESTACION SANZ'],
            ['idMunicipio'=>2061,'nombre' =>'COLONIA PROFESOR GRACIANO SANCHEZ'],
            ['idMunicipio'=>2061,'nombre' =>'EL GRULLO'],
            ['idMunicipio'=>2061,'nombre' =>'LA HERRADURA'],
            ['idMunicipio'=>2061,'nombre' =>'SAN ANTONIO HUEXOTITLA'],
            ['idMunicipio'=>2061,'nombre' =>'LA GALERA EL INFIERNILLO'],
            ['idMunicipio'=>2061,'nombre' =>'EL JARDIN'],
            ['idMunicipio'=>2061,'nombre' =>'JOSE MARIA MORELOS BUENAVISTA'],
            ['idMunicipio'=>2061,'nombre' =>'LAGUNILLA'],
            ['idMunicipio'=>2061,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2061,'nombre' =>'LA MAGDALENA SOLTEPEC'],
            ['idMunicipio'=>2061,'nombre' =>'MARIANO MATAMOROS'],
            ['idMunicipio'=>2061,'nombre' =>'COMISION FEDERAL DE ELECTRICIDAD-LA MARTINICA'],
            ['idMunicipio'=>2061,'nombre' =>'MAZAQUIAHUAC'],
            ['idMunicipio'=>2061,'nombre' =>'LAS MESAS [RANCHERIA]'],
            ['idMunicipio'=>2061,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2061,'nombre' =>'LA TRONCONERA'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHERIA OJO DE AGUA'],
            ['idMunicipio'=>2061,'nombre' =>'LA PALMA'],
            ['idMunicipio'=>2061,'nombre' =>'EL PARAISO'],
            ['idMunicipio'=>2061,'nombre' =>'EL PARDO'],
            ['idMunicipio'=>2061,'nombre' =>'LA PAZ'],
            ['idMunicipio'=>2061,'nombre' =>'LA PEDREGOSA'],
            ['idMunicipio'=>2061,'nombre' =>'LA PROVIDENCIA [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO NUEVO'],
            ['idMunicipio'=>2061,'nombre' =>'LA ROSA'],
            ['idMunicipio'=>2061,'nombre' =>'EL ROSARIO'],
            ['idMunicipio'=>2061,'nombre' =>'SAN AGUSTIN [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'EX-HACIENDA SAN BUENAVENTURA'],
            ['idMunicipio'=>2061,'nombre' =>'SAN LORENZO SOLTEPEC'],
            ['idMunicipio'=>2061,'nombre' =>'SAN PEDRO LA CUEVA'],
            ['idMunicipio'=>2061,'nombre' =>'SANTA FE'],
            ['idMunicipio'=>2061,'nombre' =>'SANTA MARIA ZOTOLUCA'],
            ['idMunicipio'=>2061,'nombre' =>'EL SANTISIMO [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'TECOMALUCAN'],
            ['idMunicipio'=>2061,'nombre' =>'SAN JOSE TEPEYAHUALCO'],
            ['idMunicipio'=>2061,'nombre' =>'EX-HACIENDA SAN JOSE TEPEYAHUALCO'],
            ['idMunicipio'=>2061,'nombre' =>'LOS TETELES'],
            ['idMunicipio'=>2061,'nombre' =>'TETZITZILICA'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO TOLTECAPA'],
            ['idMunicipio'=>2061,'nombre' =>'LAS TORTOLAS'],
            ['idMunicipio'=>2061,'nombre' =>'LA TRASQUILA'],
            ['idMunicipio'=>2061,'nombre' =>'COLONIA MAXIMO ROJAS XALOSTOC'],
            ['idMunicipio'=>2061,'nombre' =>'GUADALUPE HUEXOTITLA'],
            ['idMunicipio'=>2061,'nombre' =>'SANTA ROSA DE LIMA'],
            ['idMunicipio'=>2061,'nombre' =>'UNION EJIDAL TIERRA Y LIBERTAD'],
            ['idMunicipio'=>2061,'nombre' =>'LA LOBERA'],
            ['idMunicipio'=>2061,'nombre' =>'COLONIA DIEGO MUÑOZ CAMARGO'],
            ['idMunicipio'=>2061,'nombre' =>'LAS PALOMAS [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'SAN DIEGO QUINTANILLA'],
            ['idMunicipio'=>2061,'nombre' =>'ALTA LUZ'],
            ['idMunicipio'=>2061,'nombre' =>'MAGUEY CENIZO'],
            ['idMunicipio'=>2061,'nombre' =>'EL CORTIJO'],
            ['idMunicipio'=>2061,'nombre' =>'TLACOTLA'],
            ['idMunicipio'=>2061,'nombre' =>'AGUA ESCONDIDA'],
            ['idMunicipio'=>2061,'nombre' =>'EL PATO [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'TITICHILCO'],
            ['idMunicipio'=>2061,'nombre' =>'EJIDO SAN JOSE ATOTONILCO'],
            ['idMunicipio'=>2061,'nombre' =>'EL TECORRAL'],
            ['idMunicipio'=>2061,'nombre' =>'AGUA AZUL'],
            ['idMunicipio'=>2061,'nombre' =>'SAN BALTAZAR'],
            ['idMunicipio'=>2061,'nombre' =>'EL COLIBRI [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'NCPE LA HERRADURA'],
            ['idMunicipio'=>2061,'nombre' =>'LLANOS DE TEOPA (VALLE ESCONDIDO)'],
            ['idMunicipio'=>2061,'nombre' =>'LOMA DE ENMEDIO'],
            ['idMunicipio'=>2061,'nombre' =>'LAS MARAVILLAS [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'LA PERA'],
            ['idMunicipio'=>2061,'nombre' =>'LOS PINOS'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO DE LA PROVIDENCIA'],
            ['idMunicipio'=>2061,'nombre' =>'SAN JUAN'],
            ['idMunicipio'=>2061,'nombre' =>'SAN MARTIN [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'EL SOTOL'],
            ['idMunicipio'=>2061,'nombre' =>'ESTABLO BOVINO NUMERO 1'],
            ['idMunicipio'=>2061,'nombre' =>'LAS VIGAS'],
            ['idMunicipio'=>2061,'nombre' =>'ZACATONAL (COLONIA ITURBIDE)'],
            ['idMunicipio'=>2061,'nombre' =>'LAS ZARANDELAS'],
            ['idMunicipio'=>2061,'nombre' =>'EL PORTILLO [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'DOS BARRANCAS'],
            ['idMunicipio'=>2061,'nombre' =>'EL POTRERO MAZAYOLO [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'LA VEGA'],
            ['idMunicipio'=>2061,'nombre' =>'EL FRESNO'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO LOMA BONITA'],
            ['idMunicipio'=>2061,'nombre' =>'LOS LAURELES'],
            ['idMunicipio'=>2061,'nombre' =>'LA LOMA DEL CORTIJO'],
            ['idMunicipio'=>2061,'nombre' =>'EL DESIERTO'],
            ['idMunicipio'=>2061,'nombre' =>'EL JAGÜEY DE LOS COLUMPIOS [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'EL JAGÜEY'],
            ['idMunicipio'=>2061,'nombre' =>'EJIDO RIO BLANCO (EL DOCE)'],
            ['idMunicipio'=>2061,'nombre' =>'EL ESCORPION'],
            ['idMunicipio'=>2061,'nombre' =>'CLEMENTE MUÑOZ'],
            ['idMunicipio'=>2061,'nombre' =>'LA LOMA DEL JARDIN'],
            ['idMunicipio'=>2061,'nombre' =>'EL NACIMIENTO'],
            ['idMunicipio'=>2061,'nombre' =>'LA PARADA DEL CONEJO (LA CIENEGUILLA)'],
            ['idMunicipio'=>2061,'nombre' =>'EL PARAJE'],
            ['idMunicipio'=>2061,'nombre' =>'LA ESTRELLA'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO ESCONDIDO'],
            ['idMunicipio'=>2061,'nombre' =>'LOS SERRANOS [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'SAN PABLO EL MIRADOR'],
            ['idMunicipio'=>2061,'nombre' =>'SANTA CRUZ [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO SECO EL VIEJO'],
            ['idMunicipio'=>2061,'nombre' =>'RANCHO CAMPO DAVID'],
            ['idMunicipio'=>2061,'nombre' =>'EL TINTERO'],
            ['idMunicipio'=>2061,'nombre' =>'TLAQUEXPA'],
            ['idMunicipio'=>2061,'nombre' =>'BARRIO DE LOURDES'],
            ['idMunicipio'=>2061,'nombre' =>'EL CAPULIN'],
            ['idMunicipio'=>2061,'nombre' =>'LA TROJE'],
            ['idMunicipio'=>2061,'nombre' =>'COLONIA ALEMANIA'],
            ['idMunicipio'=>2061,'nombre' =>'LUCIA LOPEZ'],
            ['idMunicipio'=>2061,'nombre' =>'LOS MORALES'],
            ['idMunicipio'=>2061,'nombre' =>'AGUA ESCONDIDA ZOTOLUCA'],
            ['idMunicipio'=>2061,'nombre' =>'ANASTACIA MUÑOZ'],
            ['idMunicipio'=>2061,'nombre' =>'SAN JOSE (COLONIA AGUA AZUL) [ASERRADERO]'],
            ['idMunicipio'=>2061,'nombre' =>'CRUZ VERDE [RANCHO CINEGETICO]'],
            ['idMunicipio'=>2061,'nombre' =>'EL CHUPADERO'],
            ['idMunicipio'=>2061,'nombre' =>'EL DURAZNO (MEDIA LUNA)'],
            ['idMunicipio'=>2061,'nombre' =>'LEONARDO MARQUEZ (EL POZO)'],
            ['idMunicipio'=>2061,'nombre' =>'LA MESA DEL CIELO'],
            ['idMunicipio'=>2061,'nombre' =>'LOS PANCHOS'],
            ['idMunicipio'=>2061,'nombre' =>'PIEDRA BLANCA'],
            ['idMunicipio'=>2061,'nombre' =>'LOS POLOS'],
            ['idMunicipio'=>2061,'nombre' =>'LA VEGA (LA PRESA)'],
            ['idMunicipio'=>2061,'nombre' =>'LAS VIBORAS [RANCHO]'],
            ['idMunicipio'=>2061,'nombre' =>'ROBERTO GARCIA RIOS'],
            ['idMunicipio'=>2061,'nombre' =>'ROLANDO MALDONADO'],
            ['idMunicipio'=>2061,'nombre' =>'SANTA CRUZ RANCHO SECO'],
            ['idMunicipio'=>2061,'nombre' =>'EL MIRADOR (TERESA RIVERA)'],
            ['idMunicipio'=>2061,'nombre' =>'TIERRA NUEVA'],
            ['idMunicipio'=>2061,'nombre' =>'EL TORONJAL'],
            ['idMunicipio'=>2061,'nombre' =>'JUAN ARROYO'],
            ['idMunicipio'=>2061,'nombre' =>'SANTO TOMAS'],
            ['idMunicipio'=>2061,'nombre' =>'EJIDO JOSE MARIA MORELOS BUENAVISTA'],
            ['idMunicipio'=>2061,'nombre' =>'EL LLANO'],
            ['idMunicipio'=>2061,'nombre' =>'TEXOCOTLA'],
            ['idMunicipio'=>2061,'nombre' =>'EL COYOTE'],
            ['idMunicipio'=>2061,'nombre' =>'EL EMBARCADERO'],
            ['idMunicipio'=>2061,'nombre' =>'JOSE MOISES DOMINGUEZ'],
            ['idMunicipio'=>2061,'nombre' =>'LA NOPALERA'],
            ['idMunicipio'=>2061,'nombre' =>'LOS PINOS (ISRAEL OLVERA DE JESUS)'],
            ['idMunicipio'=>2061,'nombre' =>'EL COMPADRE [RANCHO]'],
            ['idMunicipio'=>2062,'nombre' =>'TOCATLAN'],
            ['idMunicipio'=>2062,'nombre' =>'ACOCOTLA'],
            ['idMunicipio'=>2063,'nombre' =>'SAN JUAN TOTOLAC'],
            ['idMunicipio'=>2063,'nombre' =>'ACXOTLA DEL RIO'],
            ['idMunicipio'=>2063,'nombre' =>'LA CANDELARIA TEOTLALPAN'],
            ['idMunicipio'=>2063,'nombre' =>'LOS REYES QUIAHUIXTLAN'],
            ['idMunicipio'=>2063,'nombre' =>'SAN FRANCISCO OCOTELULCO'],
            ['idMunicipio'=>2063,'nombre' =>'SAN MIGUEL TLAMAHUCO'],
            ['idMunicipio'=>2063,'nombre' =>'SANTIAGO TEPETICPAC'],
            ['idMunicipio'=>2063,'nombre' =>'LA TRINIDAD CHIMALPA'],
            ['idMunicipio'=>2063,'nombre' =>'CERRO DEL METECATZI'],
            ['idMunicipio'=>2063,'nombre' =>'ZARAGOZA'],
            ['idMunicipio'=>2063,'nombre' =>'EL CERRITO'],
            ['idMunicipio'=>2064,'nombre' =>'ZITLALTEPEC'],
            ['idMunicipio'=>2064,'nombre' =>'COLONIA FRANCISCO JAVIER MINA'],
            ['idMunicipio'=>2064,'nombre' =>'SAN JUAN BAUTISTA MIER'],
            ['idMunicipio'=>2064,'nombre' =>'EX-HACIENDA SAN JUAN BAUTISTA'],
            ['idMunicipio'=>2064,'nombre' =>'EL LINDERO'],
            ['idMunicipio'=>2064,'nombre' =>'SAN BERNARDINO [RANCHO]'],
            ['idMunicipio'=>2064,'nombre' =>'GUADALUPE LOS CAPULINES'],
            ['idMunicipio'=>2064,'nombre' =>'ARTURO RENDON'],
            ['idMunicipio'=>2064,'nombre' =>'JULIAN DE LA CRUZ RAMIREZ (RANCHO LA LOMA)'],
            ['idMunicipio'=>2064,'nombre' =>'RANCHO GUADALUPE (EJIDO DEL RINCON ZITLALTEPEC)'],
            ['idMunicipio'=>2065,'nombre' =>'TZOMPANTEPEC'],
            ['idMunicipio'=>2065,'nombre' =>'SAN ANDRES AHUASHUATEPEC'],
            ['idMunicipio'=>2065,'nombre' =>'SAN JUAN QUETZALCOAPAN'],
            ['idMunicipio'=>2065,'nombre' =>'SAN MATEO INOPHIL'],
            ['idMunicipio'=>2065,'nombre' =>'XALTIANQUISCO'],
            ['idMunicipio'=>2065,'nombre' =>'RANCHO AMOLTEPEC'],
            ['idMunicipio'=>2065,'nombre' =>'RANCHO TEPEYANCO'],
            ['idMunicipio'=>2065,'nombre' =>'OTONGATEPEC'],
            ['idMunicipio'=>2065,'nombre' =>'LA PROVIDENCIA LAS HUERTAS [RANCHO]'],
            ['idMunicipio'=>2065,'nombre' =>'RANCHO CRUZTITLA (COYOECA)'],
            ['idMunicipio'=>2065,'nombre' =>'EL LLANO'],
            ['idMunicipio'=>2065,'nombre' =>'MAZAPA (RANCHO LOS JUANES)'],
            ['idMunicipio'=>2065,'nombre' =>'ANDRES VIGUERAS CARBAJAL'],
            ['idMunicipio'=>2065,'nombre' =>'FRACCIONAMIENTO EL DIVINO SALVADOR'],
            ['idMunicipio'=>2065,'nombre' =>'IMELDA FLORES SANCHEZ'],
            ['idMunicipio'=>2066,'nombre' =>'XALOZTOC'],
            ['idMunicipio'=>2066,'nombre' =>'SAN PEDRO TLACOTEPEC'],
            ['idMunicipio'=>2066,'nombre' =>'GUADALUPE TEXMOLAC'],
            ['idMunicipio'=>2066,'nombre' =>'COLONIA VELAZCO'],
            ['idMunicipio'=>2066,'nombre' =>'COLONIA VENUSTIANO CARRANZA'],
            ['idMunicipio'=>2066,'nombre' =>'SANTA CRUZ ZACATZONTETLA'],
            ['idMunicipio'=>2066,'nombre' =>'COLONIA JOSE LOPEZ PORTILLO'],
            ['idMunicipio'=>2066,'nombre' =>'LOS CORRALES'],
            ['idMunicipio'=>2066,'nombre' =>'EL JAGÜEY PRIETO'],
            ['idMunicipio'=>2066,'nombre' =>'NICOLAS BRAVO [GRANJA AVICOLA]'],
            ['idMunicipio'=>2066,'nombre' =>'QUIMICHO'],
            ['idMunicipio'=>2066,'nombre' =>'FLORENCIA SANCHEZ NAVA'],
            ['idMunicipio'=>2067,'nombre' =>'XALTOCAN'],
            ['idMunicipio'=>2067,'nombre' =>'LA ASCENSION HUITZCOLOTEPEC'],
            ['idMunicipio'=>2067,'nombre' =>'LAS MESAS [COLONIA]'],
            ['idMunicipio'=>2067,'nombre' =>'LA RETAMA'],
            ['idMunicipio'=>2067,'nombre' =>'SAN SIMON TLATLAHUQUITEPEC'],
            ['idMunicipio'=>2067,'nombre' =>'SANTA BARBARA ACUICUIZCATEPEC'],
            ['idMunicipio'=>2067,'nombre' =>'TOPILCO DE JUAREZ'],
            ['idMunicipio'=>2067,'nombre' =>'SAN JOSE TEXOPA'],
            ['idMunicipio'=>2067,'nombre' =>'CUATLA'],
            ['idMunicipio'=>2067,'nombre' =>'ATZACOALCO'],
            ['idMunicipio'=>2067,'nombre' =>'AGUA BENDITA'],
            ['idMunicipio'=>2067,'nombre' =>'ESTELA SANCHEZ RODRIGUEZ'],
            ['idMunicipio'=>2067,'nombre' =>'CINCO SANTOS'],
            ['idMunicipio'=>2067,'nombre' =>'COLONIA PUERTO ARTURO'],
            ['idMunicipio'=>2067,'nombre' =>'LA LAGUNA'],
            ['idMunicipio'=>2067,'nombre' =>'LOMA MORADA'],
            ['idMunicipio'=>2067,'nombre' =>'NUEVA AMPLIACION ADOLFO RUIZ CORTINEZ'],
            ['idMunicipio'=>2067,'nombre' =>'NUEVA AMPLIACION CAMINO A XALTOCAN'],
            ['idMunicipio'=>2067,'nombre' =>'RANCHO ALVA'],
            ['idMunicipio'=>2067,'nombre' =>'RANCHO ZARATE'],
            ['idMunicipio'=>2067,'nombre' =>'TLALAPECHCO'],
            ['idMunicipio'=>2067,'nombre' =>'CAÑADA DE CHIPILA'],
            ['idMunicipio'=>2067,'nombre' =>'SAN PEDRO'],
            ['idMunicipio'=>2068,'nombre' =>'PAPALOTLA'],
            ['idMunicipio'=>2068,'nombre' =>'SAN MARCOS CONTLA'],
            ['idMunicipio'=>2068,'nombre' =>'TOCHPA'],
            ['idMunicipio'=>2068,'nombre' =>'LOMAS DEL PEDREGAL (CUACHIPOTLA)'],
            ['idMunicipio'=>2068,'nombre' =>'EL PIECITO'],
            ['idMunicipio'=>2068,'nombre' =>'SAN DIEGO BUENAVISTA'],
            ['idMunicipio'=>2068,'nombre' =>'TEPIZILA'],
            ['idMunicipio'=>2068,'nombre' =>'XALTONAC'],
            ['idMunicipio'=>2068,'nombre' =>'ZACATECOMA'],
            ['idMunicipio'=>2069,'nombre' =>'XICOHTZINCO'],
            ['idMunicipio'=>2070,'nombre' =>'SAN DIONISIO YAUHQUEMEHCAN'],
            ['idMunicipio'=>2070,'nombre' =>'EL ROSARIO OCOTOXCO'],
            ['idMunicipio'=>2070,'nombre' =>'SAN BENITO XALTOCAN'],
            ['idMunicipio'=>2070,'nombre' =>'SAN FRANCISCO TLACUILOHCAN'],
            ['idMunicipio'=>2070,'nombre' =>'SAN LORENZO TLACUALOYAN'],
            ['idMunicipio'=>2070,'nombre' =>'SANTA MARIA ATLIHUETZIAN'],
            ['idMunicipio'=>2070,'nombre' =>'SANTA ÚRSULA ZIMATEPEC'],
            ['idMunicipio'=>2070,'nombre' =>'SAN JOSE TETEL'],
            ['idMunicipio'=>2070,'nombre' =>'BARRIO DE ATENCINGO'],
            ['idMunicipio'=>2070,'nombre' =>'HUALCALTZINCO'],
            ['idMunicipio'=>2070,'nombre' =>'SAN JOSE TEPOXTLA'],
            ['idMunicipio'=>2070,'nombre' =>'CHIMALPA'],
            ['idMunicipio'=>2070,'nombre' =>'CUARTA SECCION'],
            ['idMunicipio'=>2070,'nombre' =>'TLATELPA'],
            ['idMunicipio'=>2070,'nombre' =>'LA SOLEDAD (EL CHARCO) [RANCHO]'],
            ['idMunicipio'=>2070,'nombre' =>'SERAFIN SANCHEZ GARCIA'],
            ['idMunicipio'=>2070,'nombre' =>'EL LLANO'],
            ['idMunicipio'=>2070,'nombre' =>'TEPETEXCO'],
            ['idMunicipio'=>2071,'nombre' =>'ZACATELCO'],
            ['idMunicipio'=>2071,'nombre' =>'DOMINGO ARENAS'],
            ['idMunicipio'=>2071,'nombre' =>'CAMPO DOLORES'],
            ['idMunicipio'=>2071,'nombre' =>'SANTA ELENA'],
            ['idMunicipio'=>2071,'nombre' =>'LA VEGA'],
            ['idMunicipio'=>2071,'nombre' =>'AXEXELA'],
            ['idMunicipio'=>2071,'nombre' =>'LAS LAMAS'],
            ['idMunicipio'=>2071,'nombre' =>'LA COMPUERTA'],
            ['idMunicipio'=>2071,'nombre' =>'TLATELPA'],
            ['idMunicipio'=>2071,'nombre' =>'LA BOLSA'],
            ['idMunicipio'=>2072,'nombre' =>'BENITO JUAREZ'],
            ['idMunicipio'=>2072,'nombre' =>'JAGÜEY DE NOVILLOS'],
            ['idMunicipio'=>2072,'nombre' =>'ROMAN REYES MARQUEZ'],
            ['idMunicipio'=>2073,'nombre' =>'EMILIANO ZAPATA'],
            ['idMunicipio'=>2073,'nombre' =>'AHILITLA'],
            ['idMunicipio'=>2073,'nombre' =>'EL CAPULITIC'],
            ['idMunicipio'=>2073,'nombre' =>'EL CIPRES'],
            ['idMunicipio'=>2073,'nombre' =>'COLONIA GUSTAVO DIAZ ORDAZ'],
            ['idMunicipio'=>2073,'nombre' =>'LOS ENCINOS'],
            ['idMunicipio'=>2073,'nombre' =>'RANCHO COAMILA'],
            ['idMunicipio'=>2073,'nombre' =>'RANCHO CRUZ VERDE'],
            ['idMunicipio'=>2073,'nombre' =>'EL EPAZOTE [RANCHO]'],
            ['idMunicipio'=>2073,'nombre' =>'RANCHO GUARDAMONTE'],
            ['idMunicipio'=>2073,'nombre' =>'LAS PALOMAS [RANCHO]'],
            ['idMunicipio'=>2073,'nombre' =>'SAN NICOLAS [RANCHO]'],
            ['idMunicipio'=>2073,'nombre' =>'RANCHO TRES RIOS'],
            ['idMunicipio'=>2073,'nombre' =>'RANCHO VISTA HERMOSA'],
            ['idMunicipio'=>2073,'nombre' =>'TECOAQUILLO'],
            ['idMunicipio'=>2073,'nombre' =>'TIPITZILA'],
            ['idMunicipio'=>2073,'nombre' =>'TLAXIMALOYA (LA AMAPOLA)'],
            ['idMunicipio'=>2073,'nombre' =>'ANTONIO DIAZ'],
            ['idMunicipio'=>2073,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2073,'nombre' =>'LA VENTA'],
            ['idMunicipio'=>2073,'nombre' =>'EL SALTO'],
            ['idMunicipio'=>2073,'nombre' =>'SAN ISIDRO [RANCHO]'],
            ['idMunicipio'=>2074,'nombre' =>'LAZARO CARDENAS'],
            ['idMunicipio'=>2074,'nombre' =>'EX-HACIENDA LA LAGUNA'],
            ['idMunicipio'=>2074,'nombre' =>'ATLIXTACA'],
            ['idMunicipio'=>2074,'nombre' =>'LA MANCERA [RANCHO]'],
            ['idMunicipio'=>2074,'nombre' =>'RANCHO MARIBEL'],
            ['idMunicipio'=>2074,'nombre' =>'SAN JOSE DE LA LAGUNA'],
            ['idMunicipio'=>2074,'nombre' =>'EL PALOMAR'],
            ['idMunicipio'=>2074,'nombre' =>'EL TECORRAL'],
            ['idMunicipio'=>2075,'nombre' =>'LA MAGDALENA TLALTELULCO'],
            ['idMunicipio'=>2076,'nombre' =>'SAN DAMIAN TEXOLOC'],
            ['idMunicipio'=>2076,'nombre' =>'LUIS ECHEVERRIA ÁLVAREZ'],
            ['idMunicipio'=>2076,'nombre' =>'TLAXALA'],
            ['idMunicipio'=>2077,'nombre' =>'SAN FRANCISCO TETLANOHCAN'],
            ['idMunicipio'=>2077,'nombre' =>'ACHICHIHUALOYA'],
            ['idMunicipio'=>2077,'nombre' =>'EX-RANCHO DE GUADALUPE'],
            ['idMunicipio'=>2077,'nombre' =>'SAN NICOLAS TOCHAPA'],
            ['idMunicipio'=>2077,'nombre' =>'CANTETL'],
            ['idMunicipio'=>2077,'nombre' =>'FAUSTINIANO MENDIETA ÁGUILA'],
            ['idMunicipio'=>2078,'nombre' =>'SAN JERONIMO ZACUALPAN'],
            ['idMunicipio'=>2078,'nombre' =>'LA PEDRERA'],
            ['idMunicipio'=>2078,'nombre' =>'EL TEPEYAC'],
            ['idMunicipio'=>2078,'nombre' =>'UNA FLOR EN EL PANTANO'],
            ['idMunicipio'=>2078,'nombre' =>'RANCHO VIEJO'],
            ['idMunicipio'=>2078,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2078,'nombre' =>'HUITZCOLOTLA'],
            ['idMunicipio'=>2079,'nombre' =>'SAN JOSE TEACALCO'],
            ['idMunicipio'=>2079,'nombre' =>'EL ENCINAL DOS DE MAYO'],
            ['idMunicipio'=>2079,'nombre' =>'EX-RANCHO SAN NICOLAS CUATLAPANGA'],
            ['idMunicipio'=>2079,'nombre' =>'SAN RAFAEL [RANCHO]'],
            ['idMunicipio'=>2079,'nombre' =>'COLONIA ECOLOGICA'],
            ['idMunicipio'=>2079,'nombre' =>'SAN LUIS'],
            ['idMunicipio'=>2079,'nombre' =>'SAN PEDRO MARTIR'],
            ['idMunicipio'=>2079,'nombre' =>'LA MESA GRANDE'],
            ['idMunicipio'=>2080,'nombre' =>'SAN JUAN HUACTZINCO'],
            ['idMunicipio'=>2080,'nombre' =>'TEPETZINTLA'],
            ['idMunicipio'=>2080,'nombre' =>'LUISA CARRILLO'],
            ['idMunicipio'=>2080,'nombre' =>'XALATLA'],
            ['idMunicipio'=>2080,'nombre' =>'EL ARENAL'],
            ['idMunicipio'=>2080,'nombre' =>'ANDRES CRUZ'],
            ['idMunicipio'=>2080,'nombre' =>'MILPA ALTA'],
            ['idMunicipio'=>2080,'nombre' =>'RANCHOZOLCO'],
            ['idMunicipio'=>2081,'nombre' =>'SAN LORENZO AXOCOMANITLA'],
            ['idMunicipio'=>2081,'nombre' =>'EL RANCHO'],
            ['idMunicipio'=>2081,'nombre' =>'BRIONES'],
            ['idMunicipio'=>2081,'nombre' =>'LA LAGUNA DE OXIDACION'],
            ['idMunicipio'=>2081,'nombre' =>'TEOPANZOL'],
            ['idMunicipio'=>2082,'nombre' =>'SAN LUCAS TECOPILCO'],
            ['idMunicipio'=>2082,'nombre' =>'LAS CAÑADAS'],
            ['idMunicipio'=>2082,'nombre' =>'ALAXANTO (EL LLANO)'],
            ['idMunicipio'=>2082,'nombre' =>'SAN JOSE ROSASTITLA'],
            ['idMunicipio'=>2082,'nombre' =>'TLAXCANTITLA'],
            ['idMunicipio'=>2082,'nombre' =>'TOLTECAPA'],
            ['idMunicipio'=>2082,'nombre' =>'CUAMANTZINGO'],
            ['idMunicipio'=>2082,'nombre' =>'EL LLANO'],
            ['idMunicipio'=>2082,'nombre' =>'CAUATLA'],
            ['idMunicipio'=>2082,'nombre' =>'MAXIMINO (EL LLANO)'],
            ['idMunicipio'=>2082,'nombre' =>'EL RANCHITO'],
            ['idMunicipio'=>2082,'nombre' =>'LOS ENCINOS'],
            ['idMunicipio'=>2082,'nombre' =>'CLAUDIA CHAVEZ'],
            ['idMunicipio'=>2082,'nombre' =>'GENARO ORDOÑEZ'],
            ['idMunicipio'=>2083,'nombre' =>'SANTA ANA NOPALUCAN'],
            ['idMunicipio'=>2083,'nombre' =>'LA ENLAMADERA'],
            ['idMunicipio'=>2083,'nombre' =>'SAN IGNACIO [RANCHO]'],
            ['idMunicipio'=>2083,'nombre' =>'EL ROSARIO'],
            ['idMunicipio'=>2084,'nombre' =>'SANTA APOLONIA TEACALCO'],
            ['idMunicipio'=>2084,'nombre' =>'LA ARENA'],
            ['idMunicipio'=>2084,'nombre' =>'LA LOMA'],
            ['idMunicipio'=>2084,'nombre' =>'SAN JUAN'],
            ['idMunicipio'=>2084,'nombre' =>'TECHICHILCO'],
            ['idMunicipio'=>2084,'nombre' =>'EL CRUCERO (EL CARRIL)'],
            ['idMunicipio'=>2084,'nombre' =>'PEDRO PISCIL TENIZA'],
            ['idMunicipio'=>2084,'nombre' =>'EL ESPINAL'],
            ['idMunicipio'=>2085,'nombre' =>'SANTA CATARINA AYOMETLA'],
            ['idMunicipio'=>2086,'nombre' =>'SANTA CRUZ QUILEHTLA'],
            ['idMunicipio'=>2086,'nombre' =>'AYOMETITLA'],
            ['idMunicipio'=>2087,'nombre' =>'SANTA ISABEL XILOXOXTLA'],
            
            ['idMunicipio'=>2028,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2029,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2030,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2031,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2032,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2033,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2034,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2035,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2036,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2037,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2038,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2039,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2040,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2041,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2042,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2043,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2044,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2045,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2046,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2047,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2048,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2049,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2050,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2051,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2052,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2053,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2054,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2055,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2056,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2057,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2058,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2059,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2060,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2061,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2062,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2063,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2064,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2065,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2066,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2067,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2068,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2069,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2070,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2071,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2072,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2073,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2074,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2075,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2076,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2077,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2078,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2079,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2080,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2081,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2082,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2083,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2084,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2085,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2086,'nombre' =>'SIN INFORMACION']
            
            
 	 	]);




    }
}
