<?php

use Illuminate\Database\Seeder;

class ProvidenciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_providencia_precautoria')->insert([
            [ 'nombre' => 'I. VIGILANCIA EN EL DOMICILIO DE LA VÍCTIMA O EL OFENDIDO'],
            [ 'nombre' => 'II. PROTECCIÓN POLICIAL DE LA VÍCTIMA O EL OFENDIDO'],
            [ 'nombre' => 'III. AUXILIO INMEDIATO POR INTEGRANTES DE INSTITUCIONES POLICIALES, AL DOMICILIO DONDE SE ENCUENTRE O SE LOCALICE LA VÍCTIMA U OFENDIDO EN EL MOMENTO DE SOLICITARLO'],
            [ 'nombre' => 'IV. AUXILIO DE LA FUERZA PÚBLICA PARA SOLICITAR LA INMEDIATA ENTREGA O DEVOLUCIÓN DE OBJETOS PERSONALES O DOCUMENTOS DE IDENTIFICACIÓN DE LA VÍCTIMA O EL OFENDIDO, ASÍ COMO DE SUS ASCENDIENTES, DESCENDIENTES O DEPENDIENTES ECONÓMICOS'],
            [ 'nombre' => 'V. REALIZACIÓN DEL INVENTARIO DE LOS BIENES MUEBLES E INMUEBLES DE PROPIEDAD COMÚN, PROPIEDAD DE LA VÍCTIMA O RESPECTO DE LOS CUALES SEA TITULAR DE DERECHOS, INCLUYENDO LOS IMPLEMENTOS DE TRABAJO DE LA VÍCTIMA O EL OFENDIDO'],
            [ 'nombre' => 'VI. TRASLADO DE LA VÍCTIMA O EL OFENDIDO Y DE SUS DESCENDIENTES A REFUGIO, ALBERGUE O DOMICILIO TEMPORAL'],
            [ 'nombre' => 'VII. REINGRESO DE LA VÍCTIMA O EL OFENDIDO A SU DOMICILIO UNA VEZ QUE SE SALVAGUARDE SU SEGURIDAD'],
            [ 'nombre' => 'VIII. REGISTRO O INSCRIPCIÓN EN PROGRAMAS ESTATALES DE DESARROLLO PERSONAL, SOCIAL, EDUCATIVO O LABORAL'],
            [ 'nombre' => 'IX. PROHIBICIÓN DE REALIZAR CONDUCTAS DE INTIMIDACIÓN O MOLESTIA A LA VÍCTIMA O EL OFENDIDO O PERSONAS RELACIONADAS CON ELLOS'],
            [ 'nombre' => 'X. SUSPENSIÓN TEMPORAL AL AGRESOR DEL RÉGIMEN DE VISITAS Y CONVIVENCIA CON SUS DESCENDIENTES'],
            [ 'nombre' => 'XI. POSESIÓN EXCLUSIVA DE LA VÍCTIMA SOBRE EL INMUEBLE QUE SIRVIÓ DE DOMICILIO'],
            [ 'nombre' => 'XII. OBLIGACIÓN ALIMENTARIA PROVISIONAL E INMEDIATA'],
            [ 'nombre' => 'XIII. LAS DEMÁS QUE DETERMINEN LAS DISPOSICIONES APLICABLES']
        ]);
    }
}
